### PR TITLE
#1359 - Diagonal times unit vector

### LINKED ISSUE #1359: Diagonal matrix times unit vector
```julia
julia> v = LazySets.Approximations.UnitVector(1, 2, 1.0)
2-element LazySets.Approximations.UnitVector{Float64}:
 1.0
 0.0

julia> rand(2, 2) * v
2-element Array{Float64,1}:

 0.31221484524470955
 0.12752085555322235

julia> [1.0 0.0; 0.0 1.0] * v
2-element Array{Float64,1}:
 1.0
 0.0

julia> Diagonal([1.0, 1.0]) * v
ERROR: MethodError: *(::Diagonal{Float64,Array{Float64,1}}, ::LazySets.Approximations.UnitVector{Float64}) is ambiguous. Candidates:
  *(A::AbstractArray{N,2}, e::LazySets.Approximations.UnitVector{N}) where N in LazySets.Approximations at /Users/forets/.julia/dev/LazySets/src/Approximations/template_directions.jl:62
  *(D::Diagonal, V::AbstractArray{T,1} where T) in LinearAlgebra at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/diagonal.jl:163
Possible fix, define
  *(::Diagonal{N,V} where V<:AbstractArray{N,1}, ::LazySets.Approximations.UnitVector{N})
Stacktrace:
 [1] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by mforets**
Closes #1359.

### CODE REVIEW

File: test/unit_template_directions.jl [hunk 1]
```diff
@@ -9,6 +9,12 @@ for N in [Float64, Float32, Rational{Int}]
         end
     end
 
+    # check that #1359 is fixed
+    e = UnitVector(2, 3, N(1)) # vector (0, 1, 0)
```
Comment (mforets) [inline test/unit_template_directions.jl]:
```suggestion
    e = UnitVector(2, 3, N(1)) # vector [0, 1, 0]
```
