### PR TITLE
#1207 - Concrete projection of unbounded sets

### LINKED ISSUE #1207: Quantifier elimination for projections of unbounded sets
Currently, the list of constraints of an unbounded set cannot be obtained in some cases, e.g. the projection of a halfspace:

```julia
julia> S = Approximations.project(HalfSpace([1.0, 1.0, 0.0], 1.0), [1], LinearMap)
LinearMap{Float64,HalfSpace{Float64},Float64,SparseArrays.SparseMatrixCSC{Float64,Int64}}(
  [1, 1]  =  1.0, HalfSpace{Float64}([1.0, 1.0, 0.0], 1.0))

julia> constraints_list(S)
ERROR: ArgumentError: the linear map in vertex representation for an unbounded set is not defined
Stacktrace:
 [1] _linear_map_vrep(::SparseArrays.SparseMatrixCSC{Float64,Int64}, ::HalfSpace{Float64}) at /Users/forets/.julia/dev/LazySets/src/AbstractPolyhedron_functions.jl:335
 [2] #linear_map#18(::Bool, ::Float64, ::Bool, ::Function, ::SparseArrays.SparseMatrixCSC{Float64,Int64}, ::HalfSpace{Float64}) at /Users/forets/.julia/dev/LazySets/src/AbstractPolyhedron_functions.jl:313
 [3] linear_map at /Users/forets/.julia/dev/LazySets/src/AbstractPolyhedron_functions.jl:309 [inlined]
 [4] constraints_list(::LinearMap{Float64,HalfSpace{Float64},Float64,SparseArrays.SparseMatrixCSC{Float64,Int64}}) at /Users/forets/.julia/dev/LazySets/src/LinearMap.jl:377
 [5] top-level scope at none:0
```

A robust approach would be to use [quantifier elimination](https://en.wikipedia.org/wiki/Quantifier_elimination) to find the list of constraints above (in this case, the universal set). In this direction i've seen that [Reduce](https://chakravala.github.io/Reduce.jl/latest/man/11-substitution.html#.2.5-Substitutions-for-General-Expressions-1) offers quantifier elimination, but i haven't tried it.

### PR DESCRIPTION
**Pull request by mforets**
Closes #1207.

### CODE REVIEW

File: src/Approximations/decompositions.jl [hunk 1]
```diff
@@ -636,7 +641,8 @@ function project(P::AbstractPolyhedron{N}, block::AbstractVector{Int}) where {N}
     if constrained_dimensions(P) ⊆ block
         return HPolyhedron([HalfSpace(c.a[block], c.b) for c in constraints_list(P)])
     else
-        error("the concrete projection of a polyhedron " *
-              "for a general block structure is not implemented yet")
```
Comment (schillic) [inline src/Approximations/decompositions.jl]: The documentation still says that this case is not supported and should be updated.

Comment (mforets) [reply src/Approximations/decompositions.jl]: Good catch, i have updated the Algorithm section.

I've also hard-coded the return type, because this is what the function's "Output" documentation says.

Comment (mforets) [reply src/Approximations/decompositions.jl]: (Note that the concrete linear map, although it will operate in hrep, it may return other set types eg. HPolygon's iirc).

Comment (schillic) [reply src/Approximations/decompositions.jl]: > I've also hard-coded the return type, because this is what the function's "Output" documentation says.

You know that you can also change the documentation instead :wink:

Comment (mforets) [reply src/Approximations/decompositions.jl]: Yes, but i would rather move that (breaking) change for consideration in a follow-up issue. In general, i think it's a good idea that the returned type is "closer" to the actual set. But for consistency we should also apply the same logic for existing case; in particular, note that the existing `constrained_dimensions(P) ⊆ block` case *always* returns an `HPolyhedron`, irrespective of the set dimension.

Comment (mforets) [reply src/Approximations/decompositions.jl]: Should i resolve this conversation? I forgot what we wanted to do here...

Comment (schillic) [reply src/Approximations/decompositions.jl]: > Yes, but i would rather move that (breaking) change for consideration in a follow-up issue. In general, i think it's a good idea that the returned type is "closer" to the actual set.

This is what you suggested. I leave it to you to decide what you want :wink:

Comment (mforets) [reply src/Approximations/decompositions.jl]: Ok, ill open an issue. The proposal here is to return an interval / halfspace / line / hpolygon / hpolytope / hpolyhedron depending on the result of the projection..
