### PR TITLE
#1049 - Default implementation of isempty for polyhedra

### LINKED ISSUE #1049: Default implementation of isempty for polyhedra
```julia
julia> using LazySets

julia> P = HPolytope([LazySets.HalfSpace([1.0], 18.1)]);

julia> isempty(P)
ERROR: AssertionError: this function needs the package 'Polyhedra' to be loaded
Stacktrace:
 [1] default_polyhedra_backend(::HPolytope{Float64}, ::Type) at /Users/forets/.julia/dev/LazySets/src/AbstractPolytope.jl:133
 [2] isempty(::HPolytope{Float64}) at /Users/forets/.julia/dev/LazySets/src/HPolyhedron.jl:738
 [3] top-level scope at none:0
```

This can be done without calling Polyhedra by refactoring the recent method in `is_intersection_empty`.

### PR DESCRIPTION
**Pull request by schillic**
Closes #1049.

### CODE REVIEW

File: src/HPolyhedron.jl [hunk 1]
```diff
@@ -706,38 +706,70 @@ function singleton_list(P::HPolyhedron{N}) where {N<:Real}
...
+        result = Polyhedra.isempty(polyhedron(P; backend=backend), solver)
+        if result
+            return witness ? (true, N[]) : true
+        elseif witness
+            error("witness production is not supported yet")
+        else
+            return false
+        end
+    else
+        A, b = tosimplehrep(P)
```
Comment (mforets) [inline src/HPolyhedron.jl]: what do you think about factoring out the stuff inside the `else` into a function that receives a list of constraints and checks whether they are feasible? this same function can be used in `is_intersection_empty`, i believe

Comment (schillic) [reply src/HPolyhedron.jl]: Noted in  #1057.
