### PR TITLE
#306 - Revise `SparseMatrixExp`

### LINKED ISSUE #306: warn in `SparseMatrixExp` constructor that the type is sparse
the lazy matrix exponential is only defined for sparse matrices; we could have a better error message than:

```julia
julia> A = SparseMatrixExp(rand(2, 2))
ERROR: MethodError: Cannot `convert` an object of type Array{Float64,2} to an object of type LazySets.SparseMatrixExp
This may have arisen from a call to the constructor LazySets.SparseMatrixExp(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] LazySets.SparseMatrixExp(::Array{Float64,2}) at ./sysimg.jl:77
```

something along the lines:

```julia
SparseMatrixExp(M::Matrix{N}) where {N} =
        error("only sparse matrices can be used to create a `SparseMatrixExp`")
```

an example in the docstring would also help.

### PR DESCRIPTION
**Pull request by mforets**
Closes #306.

- [x]  extend SparseMatrixExp examples
- [x] add constructor error for dense
- [x] add an example to `ExponentialMap`

### CODE REVIEW

File: src/ExponentialMap.jl [hunk 1]
```diff
@@ -21,6 +21,33 @@ Type that represents the matrix exponential, ``\\exp(M)``, of a sparse matrix.
 
 - `M` -- sparse matrix
 
+### Examples
+
+Take for exammple a random sparse matrix;
```
Comment (schillic) [inline src/ExponentialMap.jl]: Should this be a colon (`:`)?

File: src/ExponentialMap.jl [hunk 2]
```diff
@@ -21,6 +21,33 @@ Type that represents the matrix exponential, ``\\exp(M)``, of a sparse matrix.
...
+they return row and column vectors (or matrices). For example:
+
+```jldoctest SparseMatrixExp_constructor
+julia> get_row(E, 10); # compute E[10, :]
+
+julia> get_column(E, 10); # compute E[:, 10]
+
+julia> get_rows(E, [10]); # same as get_row(E, 10) but a 1x100 matrix is returned
+
+julia> get_columns(E, [10]); # same as get_row(E, 10) but a 100x1 matrix is returned
```
Comment (schillic) [inline src/ExponentialMap.jl]: "same as get_column"

**Comment by mforets** [comment]
thanks for the review.
