### PR TITLE
#317 - Handling of non-square SparseMatrixExp

### LINKED ISSUE #317: Handling of non-square SparseMatrixExp
Currently we allow to create a `SparseMatrixExp` that is not square, but most operations, including printing, will crash.
Should we add a dimension check in the constructor?
At least we should document that the matrix must be square, even if that is implicitly clear.

### PR DESCRIPTION
**Pull request by mforets**
Closes #317.

### CODE REVIEW

File: src/LazyOperations/ExponentialMap.jl [hunk 1]
```diff
@@ -54,10 +57,17 @@ julia> get_columns(E, [10]); # same as get_column(E, 10) but a 100x1 matrix is r
...
-[Expokit](https://github.com/acroy/Expokit.jl) package.
+[Expokit](https://github.com/acroy/Expokit.jl) package. Hence, you will have to
+install and load this optional dependency to have access to the functionality
+of `SparseMatrixExp`.
 """
 struct SparseMatrixExp{N, MN<:AbstractSparseMatrix{N}} <: AbstractMatrix{N}
     M::MN
+    function SparseMatrixExp(M::MN) where {N, MN<:AbstractSparseMatrix{N}}
+        @assert size(M, 1) == size(M, 2) "the lazy matrix exponential `SparseMatrixExp` " *
+        "requires the given matrix to be square, but it has size $(size(M))"
```
Comment (schillic) [inline src/LazyOperations/ExponentialMap.jl]:
```suggestion
            "requires the given matrix to be square, but it has size $(size(M))"
```
