### PR TITLE
#1066 - Add linear map for a halfspace

### LINKED ISSUE #1066: Concrete linear map of a halfspace
```julia
julia> M = rand(2, 2); H = rand(HalfSpace, dim=2);

julia> linear_map(M, H)
ERROR: MethodError: no method matching linear_map(::Array{Float64,2}, ::HalfSpace{Float64})

Closest candidates are:
  linear_map(::AbstractArray{N<:Real,2}, ::AbstractPolygon{N<:Real}; output_type) where N<:Real at /Users/forets/.julia/dev/LazySets/src/AbstractPolygon.jl:2
07
  linear_map(::AbstractArray{N<:Real,2}, ::ZeroSet{N<:Real}) where N<:Real at /Users/forets/.julia/dev/LazySets/src/ZeroSet.jl:178
  linear_map(::AbstractArray{N<:Real,2}, ::AbstractSingleton{N<:Real}) where N<:Real at /Users/forets/.julia/dev/LazySets/src/AbstractSingleton.jl:166
  ...
Stacktrace:
 [1] top-level scope at none:0

julia> HPolyhedron([H])
HPolyhedron{Float64}(HalfSpace{Float64}[HalfSpace{Float64}([0.286447, -1.76997], -0.666374)])

julia> linear_map(M, HPolyhedron([H]))
HPolyhedron{Float64}(HalfSpace{Float64}[HalfSpace{Float64}([-2.16862, 1.86982], -0.666374)])
```

### PR DESCRIPTION
**Pull request by mforets**
Closes #1066.

### CODE REVIEW

File: test/unit_HalfSpace.jl [hunk 1]
```diff
@@ -81,4 +81,10 @@ for N in [Float64, Rational{Int}, Float32]
     hs4 = HalfSpace(N[-1, 0], N(0)) # x >= 0
     empty_intersection, v = is_intersection_empty(hs1, hs4, true)
     @test !is_intersection_empty(hs1, hs4) && !empty_intersection && v ∈ hs1 && v ∈ hs4
+
+    # test linear map of a half-space
+    H = HalfSpace(N[1.0, -1.0], 0.0) # x <= y
```
Comment (mforets) [inline test/unit_HalfSpace.jl]:
```suggestion
    H = HalfSpace(N[1.0, -1.0], N(0.0)) # x <= y
```
