### PR TITLE
#2327 - Hyperplane-Hyperplane intersection emptiness

### LINKED ISSUE #2327: Hyperplane-Hyperplane intersection emptiness
```julia
julia> isdisjoint(rand(Hyperplane), rand(Hyperplane))
ERROR: the support vector for the hyperplane with normal direction [0.85425817454693, -0.8751753682278215]
is not defined along a direction [-0.5262298487743711, 1.0888813935440376]
```
This should be a simple system of linear equations.

### PR DESCRIPTION
**Pull request by schillic**
Closes #2327.

### CODE REVIEW

File: src/ConcreteOperations/isdisjoint.jl [hunk 1]
```diff
@@ -744,12 +744,31 @@ function is_intersection_empty(hp::Union{Hyperplane{N}, Line2D{N}},
...
 function is_intersection_empty(hp1::Union{Hyperplane{N}, Line2D{N}},
                                hp2::Union{Hyperplane{N}, Line2D{N}},
                                witness::Bool=false
                               ) where {N<:Real}
-    return is_intersection_empty_helper_hyperplane(hp1, hp2, witness)
+    if isequivalent(hp1, hp2)
+        res = false
+        if witness
+            w = an_element(hp1)
+        end
```
Comment (schillic) [inline src/ConcreteOperations/isdisjoint.jl:755]: This case is needed because `intersection(hp1, hp2)` would return an `HPolyhedron` and then `an_element` would return `[Inf, Inf]`.

File: src/ConcreteOperations/isdisjoint.jl [hunk 2]
```diff
@@ -744,12 +744,31 @@ function is_intersection_empty(hp::Union{Hyperplane{N}, Line2D{N}},
...
+    else
+        cap = intersection(hp1, hp2)
+        res = cap isa EmptySet
```
Comment (schillic) [inline src/ConcreteOperations/isdisjoint.jl:758]: I first tried solving a linear system, but that throws an exception if there is no intersection.

This implementation is not really efficient, but at least it does not crash as in `master`...

Comment (mforets) [reply src/ConcreteOperations/isdisjoint.jl:758]: to check disjointness of Line2D there is [this approach](https://github.com/JuliaReach/LazySets.jl/blob/master/src/ConcreteOperations/intersection.jl#L86)

Comment (mforets) [reply src/ConcreteOperations/isdisjoint.jl:758]: for the n-dimensional hyperplane case, there is a full length explanation [here](https://math.stackexchange.com/questions/2360603/how-to-find-the-intersection-of-two-hyperplanes-in-n-dimensions)

Comment (schillic) [reply src/ConcreteOperations/isdisjoint.jl:758]: > to check disjointness of Line2D there is this approach

Yep, that will be called by `intersection` :sweat_smile:
