### PR TITLE
#1662 - Dimensional check in zonotope constructor

### LINKED ISSUE #1662: Dimensional check in zonotope constructor
Add a dimensional check in the Zonotope's inner constructor such that eg. the following raises an assertion error:

```julia
julia> Q = Zonotope([1., 1], [[0. 0]; [0.5 0]; [0. 0.5]; [0. 0]])
Zonotope{Float64}([1.0, 1.0], [0.0 0.0; 0.5 0.0; 0.0 0.5; 0.0 0.0])
```

cc: @SebastianGuadalupe

### PR DESCRIPTION
**Pull request by SebastianGuadalupe**
Closes #1662.

### CODE REVIEW

File: src/Zonotope.jl [hunk 1]
```diff
@@ -89,6 +89,8 @@ struct Zonotope{N<:Real} <: AbstractZonotope{N}
 
     function Zonotope(center::AbstractVector{N}, generators::AbstractMatrix{N};
                       remove_zero_generators::Bool=true) where {N<:Real}
+        @assert length(center) == size(generators, 1) "the dimension of the " *
+        "center($(length(center))) and the generators($(size(generators, 1))) need to match"
```
Comment (schillic) [inline src/Zonotope.jl]:
```suggestion
            "center ($(length(center))) and the generators " *
            "($(size(generators, 1))) need to match"
```

**Comment by mforets** [comment]
@SebastianGuadalupe can you rebase w/master?

**Comment by schillic** [comment]
To fix the test failure, please fix this line:
https://github.com/JuliaReach/LazySets.jl/blob/38cae572067ad9867a6856945b4c8314d23ac7fb/test/check_method_ambiguity_binary.jl#L64

It should be:
```julia
        Zonotope(zeros(1), [1. 2.;])
```
