### PR TITLE
#2466 - Fallback conversion to VPolytope

### LINKED ISSUE #2466: Fallback conversion to VPolytope
A method similar to this one https://github.com/JuliaReach/LazySets.jl/blob/a4bb2f5f2a8d5e444fee50ddeac87b980ba85107/src/convert.jl#L153  but for VPolytope seems to be missing.

```julia
convert(VPolytope, rand(3, 3) * rand(BallInf, dim=3))

MethodError: Cannot `convert` an object of type 
  LinearMap{Float64,BallInf{Float64,Array{Float64,1}},Float64,Array{Float64,2}} to an object of type 
  VPolytope
Closest candidates are:
  convert(::Type{VPolytope}, !Matched::VPolytope) at /home/mforets/.julia/dev/LazySets/src/convert.jl:8
  convert(::Type{VPolytope}, !Matched::HPolytope) at /home/mforets/.julia/dev/LazySets/src/convert.jl:239
  convert(::Type{VPolytope}, !Matched::AbstractPolytope) at /home/mforets/.julia/dev/LazySets/src/convert.jl:110
  ...

Stacktrace:
 [1] top-level scope at In[29]:1
 [2] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1091

```

### PR DESCRIPTION
**Pull request by mforets**
Closes #2466.

### CODE REVIEW

File: src/convert.jl [hunk 1]
```diff
@@ -218,6 +218,31 @@ function convert(::Type{HPolytope}, P::VPolytope)
...
+"""
+    convert(::Type{VPolytope}, X::LazySet; [prune]::Bool=true)
+
+Generic conversion to polytope in vertex representation.
+
+### Input
+
+- `type`  -- target type
+- `X`     -- set
+- `prune` -- (optional, default: `true`)
```
Comment (schillic) [inline src/convert.jl:230]:
```suggestion
- `prune` -- (optional, default: `true`) option to remove redundant vertices
```

File: src/convert.jl [hunk 2]
```diff
@@ -218,6 +218,31 @@ function convert(::Type{HPolytope}, P::VPolytope)
...
+
+### Output
+
+The given set represented as a polytope in vertex representation.
+
+### Algorithm
+
+We compute the list of vertices of `X` and wrap the result in a polytope in
+vertex representation, `VPolytope`. Use the option `prune` to select whether or not
+to apply a convex hull previous to the construction of the polytope.
```
Comment (schillic) [inline src/convert.jl:240]:
```suggestion
to remove redundant vertices previous to the construction of the polytope.
```
"convex hull" is an implementation detail and the effect is not necessarily clear.

**Review by schillic — APPROVED** [review]
