### PR TITLE
#2102 - Fix numeric issue with is_right_turn

### LINKED ISSUE #2102: Empty intersection in HPolygon's addconstraints! resp. isredundant
The intersection of the lines corresponding to two-dimensional constraints can be empty due to numerical issues. Instead of raising an exception, we should add the constraint, making the polygon empty.
In the example below, constraints `Hs[2]` and `Hs[3]` are parallel, and so are `Hs[1]` and `H`. Here the intersection is nonempty.

```julia
julia> Hs = [HalfSpace([0.05125918978413134, 0.0], 0.956012965730266),
 HalfSpace([-0.0363879863894044, 0.3036279569180349], -0.370213880061176),
 HalfSpace([0.03529692609786872, -0.2945239519959644], 0.36249837124872736)];

julia> H = HalfSpace([-0.012707966980287463, 3.809113859067846e-15], -0.2348665397215645);

julia> addconstraint!(Hs, H)
ERROR: AssertionError: $(Expr(:escape, :(cap isa Singleton)))
Stacktrace:
 [1] macro expansion at /.julia/dev/LazySets/src/Assertions/Assertions.jl:23 [inlined]
 [2] isredundant(::HalfSpace{Float64,Array{Float64,1}}, ::HalfSpace{Float64,Array{Float64,1}}, ::HalfSpace{Float64,Array{Float64,1}}) at /.julia/dev/LazySets/src/Interfaces/AbstractHPolygon.jl:320
 [3] #addconstraint!#315(::Bool, ::Bool, ::typeof(addconstraint!), ::Array{HalfSpace{Float64,Array{Float64,1}},1}, ::HalfSpace{Float64,Array{Float64,1}}) at /.julia/dev/LazySets/src/Interfaces/AbstractHPolygon.jl:460
 [4] addconstraint!(::Array{HalfSpace{Float64,Array{Float64,1}},1}, ::HalfSpace{Float64,Array{Float64,1}}) at /.julia/dev/LazySets/src/Interfaces/AbstractHPolygon.jl:436
 [5] top-level scope at REPL[31]:1
 [6] eval(::Module, ::Any) at ./boot.jl:330
 [7] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:86
 [8] run_backend(::REPL.REPLBackend) at /.julia/packages/Revise/Pcs5V/src/Revise.jl:1073
 [9] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by schillic**
Closes #2102.

### CODE REVIEW

File: src/Sets/VPolygon.jl [hunk 1]
```diff
@@ -397,12 +397,7 @@ julia> [4.5, 3.1] ∈ P
 false
 julia> [4.5, 3.0] ∈ P
 true
-julia> [4.4, 3.4] ∈ P  #  point lies on the edge -> floating-point error
-false
-julia> P = VPolygon([[2//1, 3//1], [3//1, 1//1], [5//1, 1//1], [4//1, 5//1]];
-                     apply_convex_hull=false);
-
-julia> [44//10, 34//10] ∈ P  #  with rational numbers the answer is correct
+julia> [4.4, 3.4] ∈ P  #  point lies on the edge
```
Comment (mforets) [inline src/Sets/VPolygon.jl:400]: nice! the values computed by `right_turn` for this test are

```julia
julia> [4.4, 3.4] ∈ P # master
false

julia> [4.4, 3.4] ∈ P 

4.000000000000001
5.200000000000001
4.8
-1.3322676295501878e-15
false
```
