### PR TITLE
#658 - Check for intersection of a compact set and a HalfSpace

### LINKED ISSUE #658: Check for intersection of a compact set and a HalfSpace
This is a special case of #641.

EDIT: The previous version did not work, I fixed it.
The idea is to compute the support function in the opposite direction of the `HalfSpace`'s normal vector and then compare to the `HalfSpace`'s constraint.

### PR DESCRIPTION
**Pull request by schillic**
Closes #658.

### CODE REVIEW

File: src/is_intersection_empty.jl [hunk 1]
```diff
@@ -680,6 +680,55 @@ function is_intersection_empty(hp::Union{Hyperplane{N}, Line{N}},
...
+### Notes
+
+We assume that `X` is compact.
+Otherwise, the support vector queries may fail.
+
+### Algorithm
+
+A compact convex set intersects with a half-space iff the support vector in
+the negative direction of the half-space's normal vector ``a`` is contained in
+the half-space: ``σ(-a) ∈ hs``.
```
Comment (mforets) [inline src/is_intersection_empty.jl]: I disagree. Take `B = Ball2(zeros(2), 1.0)` and `H = HalfSpace([1.0, 0.0], 1.0) # x <= 0`. Then `is_intersection_empty(B, H)` should be `true` but it is returning `false`.

I think the condition is:  (`is_intersection_empty` is `true`) iff ``\rho_X(n) - b >= 0``.

Comment (schillic) [reply src/is_intersection_empty.jl]: You are right, the condition should be *every support vector* in general, so my implementation does not work. Yours does.

> Then is_intersection_empty(B, H) should be true

No, why? The constraint says x <= 1 and the ball is completely contained in that set, so the intersection is not empty.

Comment (schillic) [reply src/is_intersection_empty.jl]: > You are right, the condition should be every support vector in general, so my implementation does not work.

I take that back. For half-spaces, if *one* support vector is inside, *all* of them are (because they all lie on a hyperplane, which must be beyond the half-space's hyperplane.
