### PR TITLE
#1052 - Add constraints list of a lazy linear map

### LINKED ISSUE #1052: Add constraints list of a lazy linear map
```julia
julia> M = rand(2, 2);

julia> H = rand(Hyperrectangle);

julia> M * H
LinearMap{Float64,Hyperrectangle{Float64},Float64,Array{Float64,2}}([0.564647 0.685825; 0.526256 0.74641], Hyperrectangle{Float64}([-0.995348, 1.90843], [0.365646, 0.331539]))

julia> constraints_list(M * H)
ERROR: MethodError: no method matching constraints_list(::LinearMap{Float64,Hyperrectangle{Float64},Float64,Array{Float64,2}})
Closest candidates are:
  constraints_list(::LazySets.HalfSpace{N<:Real}) where N<:Real at /Users/forets/.julia/dev/LazySets/src/HalfSpace.jl:244
  constraints_list(::AbstractHyperrectangle{N<:Real}) where N<:Real at /Users/forets/.julia/dev/LazySets/src/AbstractHyperrectangle.jl:80
  constraints_list(::AbstractHPolygon{N<:Real}) where N<:Real at /Users/forets/.julia/dev/LazySets/src/AbstractHPolygon.jl:153
  ...
Stacktrace:
 [1] top-level scope at none:0

julia> constraints_list(linear_map(M, H))
4-element Array{LazySets.HalfSpace{Float64},1}:
 LazySets.HalfSpace{Float64}([-0.317958, 0.341153], 0.08192979927379967) 
 LazySets.HalfSpace{Float64}([0.317634, -0.291852], -0.01622230506983325)
 LazySets.HalfSpace{Float64}([-0.31703, 0.291298], 0.034995181218652055) 
 LazySets.HalfSpace{Float64}([0.201603, -0.21631], -0.03657033960105904) 
```

### PR DESCRIPTION
**Pull request by schillic**
Closes #1052.

### CODE REVIEW

File: src/LinearMap.jl [hunk 1]
```diff
@@ -328,7 +329,7 @@ A list of vertices.
 
 ### Algorithm
 
-We assume that the underlying set `X` is polytopic.
+We assume that the underlying set `X` is polyhedral.
```
Comment (mforets) [inline src/LinearMap.jl]: what about using an interface for the dispatch? `LinearMap{N, S} where {S<:AbstractPolytope}`

Comment (schillic) [reply src/LinearMap.jl]: 1. This PR is about `constraints_list`.
2. This is the old dispute about lazy operations. In this PR (`constraints_list`) I used the interface as you did in `Intersection`, but to be honest now things are inconsistent.
