### PR TITLE
#1033 - Use infix / negated unicode characters

### LINKED ISSUE #1033: Use negated unicode characters
In the tests we often use `!(x ∈ X)` and `!(X ⊆ Y)`. Instead, we can use `x ∉ X` and `X ⊈ Y`.

Warning: `⊈` does not work in Julia v0.6 out of the box.

### PR DESCRIPTION
**Pull request by schillic**
Closes #1033.

### CODE REVIEW

File: test/unit_Singleton.jl [hunk 1]
```diff
@@ -55,8 +55,8 @@ for N in [Float64, Rational{Int}, Float32]
 
     # membership
     S = Singleton(N[1, 1])
-    !∈(N[0.9, 1.1], S)
-    ∈(N[1, 1], S)
+    N[0.9, 1.1] ∉ S
```
Comment (mforets) [inline test/unit_Singleton.jl]:
```suggestion
    @test N[0.9, 1.1] ∉ S
```

File: test/unit_Singleton.jl [hunk 2]
```diff
@@ -55,8 +55,8 @@ for N in [Float64, Rational{Int}, Float32]
...
+    N[1, 1] ∈ S
```
Comment (mforets) [inline test/unit_Singleton.jl]:
```suggestion
    @test N[1, 1] ∈ S
```
