### PR TITLE
#2293 - Disjointness check for Line2D

### LINKED ISSUE #2293: isdisjoint of two Line2D
```julia
julia> L1, L2 = rand(Line2D), rand(Line2D);

julia> isdisjoint(L1, L2)
ERROR: the support vector for the hyperplane with normal direction [0.18803394272269977, -1.5674064521394673] is not defined along a direction [-1.0591295546190405, -1.3334402850411569]
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] #σ_helper#130 at /home/sguadalupe/.julia/dev/LazySets/src/Sets/Hyperplane.jl:384 [inlined]
 [3] σ at /home/sguadalupe/.julia/dev/LazySets/src/Sets/Hyperplane.jl:125 [inlined]
 [4] σ at /home/sguadalupe/.julia/dev/LazySets/src/Sets/Line2D.jl:145 [inlined]
 [5] is_intersection_empty_helper_hyperplane at /home/sguadalupe/.julia/dev/LazySets/src/ConcreteOperations/isdisjoint.jl:640 [inlined]
 [6] is_intersection_empty(::Line2D{Float64,Array{Float64,1}}, ::Line2D{Float64,Array{Float64,1}}, ::Bool) at /home/sguadalupe/.julia/dev/LazySets/src/ConcreteOperations/isdisjoint.jl:728 (repeats 2 times)
 [7] top-level scope at REPL[4]:1
```

### PR DESCRIPTION
**Pull request by mforets**
Closes #2293.

### CODE REVIEW

File: src/ConcreteOperations/isdisjoint.jl [hunk 1]
```diff
@@ -1573,3 +1573,44 @@ end
...
+"""
+function is_intersection_empty(L1::Line2D{N}, L2::Line2D{N}, witness::Bool=false) where {N<:Real}
+    disjoint, _ = _isdisjoint(L1, L2)
+    if !witness
+        return disjoint
+    else
+        if disjoint
+            return (true, [])
+        else
+            return (false, an_element(intersection(L1, L2)))
```
Comment (schillic) [inline src/ConcreteOperations/isdisjoint.jl:1606]: Apparently we do not have `an_element` for `Line2D` and the intersection can be of that type.
```
LoadError: MethodError: no method matching element(::Line2D{Float64,SingleEntryVector{Float64}})
```

Comment (mforets) [reply src/ConcreteOperations/isdisjoint.jl:1606]:
```julia
julia> L = rand(Line2D)
Line2D{Float64,Array{Float64,1}}([-0.6939299436010502, 0.856395234301458], 0.6582110708021547)

julia> an_element(L)
2-element Array{Float64,1}:
 0.28559678873468836
 1.0
```

Comment (schillic) [reply src/ConcreteOperations/isdisjoint.jl:1606]: Oh, sorry, I misread that error message.

```julia
  LoadError: MethodError: no method matching element(::Line2D{Float64,SingleEntryVector{Float64}})
```

Comment (mforets) [reply src/ConcreteOperations/isdisjoint.jl:1606]: The error can be reproduced with:

```julia
julia> N = Float64; H1 = Hyperrectangle(N[1, 1], N[2, 2])
Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}([1.0, 1.0], [2.0, 2.0])

julia> vlist = vertices_list(H1)
4-element Array{Array{Float64,1},1}:

 [3.0, 3.0]
 [-1.0, 3.0]
 [3.0, -1.0]
 [-1.0, -1.0]

julia> H1pol = convert(HPolygon, H1)
HPolygon{Float64,LazySets.Arrays.SingleEntryVector{Float64}}(HalfSpace{Float64,LazySets.Arrays.SingleEntryVector{Float64}}[HalfSpace{Float64,LazySets.Arrays.Si
ngleEntryVector{Float64}}([1.0, 0.0], 3.0), HalfSpace{Float64,LazySets.Arrays.SingleEntryVector{Float64}}([0.0, 1.0], 3.0), HalfSpace{Float64,LazySets.Arrays.S
ingleEntryVector{Float64}}([-1.0, 0.0], 1.0), HalfSpace{Float64,LazySets.Arrays.SingleEntryVector{Float64}}([0.0, -1.0], 1.0)])

julia> vlist = vertices_list(H1pol)
ERROR: MethodError: no method matching element(::Line2D{Float64,LazySets.Arrays.SingleEntryVector{Float64}})
Closest candidates are:
  element(::Singleton{N,VN} where VN<:AbstractArray{N,1}) where N<:Real at /home/mforets/.julia/dev/LazySets/src/Sets/Singleton.jl:37
  element(::Singleton{N,VN} where VN<:AbstractArray{N,1}, ::Int64) where N<:Real at /home/mforets/.julia/dev/LazySets/src/Sets/Singleton.jl:55
  element(::ZeroSet{N}) where N<:Real at /home/mforets/.julia/dev/LazySets/src/Sets/ZeroSet.jl:43
  ...
Stacktrace:
 [1] vertices_list(::HPolygon{Float64,LazySets.Arrays.SingleEntryVector{Float64}}; apply_convex_hull::Bool, check_feasibility::Bool) at /home/mforets/.julia/de
v/LazySets/src/Interfaces/AbstractHPolygon.jl:150
 [2] vertices_list(::HPolygon{Float64,LazySets.Arrays.SingleEntryVector{Float64}}) at /home/mforets/.julia/dev/LazySets/src/Interfaces/AbstractHPolygon.jl:140
 [3] top-level scope at REPL[14]:1
```

so at some point the `vertices_list` function expects a singleton but receives a line.

Comment (mforets) [reply src/ConcreteOperations/isdisjoint.jl:1649]: The last commits fixes this error.

File: test/unit_overapproximate.jl [hunk 2]
```diff
@@ -153,8 +153,8 @@ for N in [Float64, Float32]
     ε = N(0.01)
     p = tovrep(overapproximate(b, ε))
     for v in vertices_list(p)
-    @test norm(v) >= N(1)
-    @test norm(v) <= N(1 + ε)
+    @test _geq(norm(v), N(1))
```
Comment (mforets) [inline test/unit_overapproximate.jl:156]: this was needed because with the new version it was giving

```julia
  Expression: norm(v) >= N(1)
   Evaluated: 0.99999994f0 >= 1.0f0
Stacktrace:
 [1] top-level scope at /home/mforets/.julia/dev/LazySets/test/unit_overapproximate.jl:156
 [2] include(::String) at ./client.jl:439
 [3] macro expansion at /home/mforets/.julia/dev/LazySets/test/runtests.jl:140 [inlined]
 [4] macro expansion at /home/mforets/Tools/julia-1.4.1-linux-x86_64/julia-1.4.1/share/julia/stdlib/v1.4/Test/src/Test.jl:1113 [inlined]
 [5] macro expansion at /home/mforets/.julia/dev/LazySets/test/runtests.jl:140 [inlined]
 [6] macro expansion at ./util.jl:175 [inlined]
 [7] top-level scope at /home/mforets/.julia/dev/LazySets/test/runtests.jl:140
...
```

Comment (schillic) [reply test/unit_overapproximate.jl:156]: Okay, but the second test `@test norm(v) <= N(1 + ε)` should still work, right?

Comment (schillic) [reply test/unit_overapproximate.jl:156]: Sorry, the new test was hidden here.

File: src/ConcreteOperations/isdisjoint.jl [hunk 3]
```diff
@@ -1616,3 +1616,48 @@ end
...
+# the lines do not intersect <=> det is zero and they are not identical
+function _isdisjoint(L1::Line2D, L2::Line2D)
+    det = _det(L1, L2)
+    disjoint = isapproxzero(det) && !isapprox(L1.b, L2.b)
+    return disjoint
+end
+
+@inline function _det(L1::Line2D, L2::Line2D)
+    @inbounds det = L1.a[1] * L2.a[2] - L1.a[2] * L2.a[1]
+end
```
Comment (schillic) [inline src/ConcreteOperations/isdisjoint.jl:1663]: (Maybe move to `Line2D.jl`.)

File: src/ConcreteOperations/isdisjoint.jl [hunk 4]
```diff
@@ -1616,3 +1616,48 @@ end
...
+  * `(true, [])` iff ``L1 ∩ L2 = ∅``
+  * `(false, v)` iff ``L1 ∩ L2 ≠ ∅`` and ``v ∈ L1 ∩ L2``
+"""
+function is_intersection_empty(L1::Line2D{N}, L2::Line2D{N}, witness::Bool=false) where {N<:Real}
+    disjoint = _isdisjoint(L1, L2)
+    if !witness
+        return disjoint
+    else
+        if disjoint
+            return (true, [])
```
Comment (schillic) [inline src/ConcreteOperations/isdisjoint.jl:1647]:
```suggestion
            return (true, N[])
```

File: src/ConcreteOperations/isdisjoint.jl [hunk 5]
```diff
@@ -1616,3 +1616,48 @@ end
...
+        else
+            return (false, an_element(intersection(L1, L2)))
```
Comment (schillic) [inline src/ConcreteOperations/isdisjoint.jl:1649]: (`intersection(L1, L2)` recomputes many things, including the determinant. We could have a helper method that gives the intersection point. But we can do that another time.)

**Review by schillic — APPROVED** [review]

File: src/ConcreteOperations/isdisjoint.jl (hunk 5 above)
Comment (mforets) [reply src/ConcreteOperations/isdisjoint.jl:1649]: true. i've opened a new issue
