### PR TITLE
#3629 -  Fix `intersection` of `LineSegments`

### LINKED ISSUE #3629: Wrong intersection of line segments
I'm currently puzzled by this intersection error.

```julia
import Luxor
using LazySets
Luxor.@png begin 
	a1 = Float32[-34.67, -46.06]
	a2 = Float32[-13.03, -49.77]

	b1 = Float32[-22.473152, -48.13686]
	b2 = Float32[-19.031397, -48.730015]
	Luxor.scale(20)
	Luxor.translate(20.67, 46.06)
	Luxor.line(Luxor.Point(a1...), Luxor.Point(a2...), :stroke)
	Luxor.sethue("red")
	Luxor.line(Luxor.Point(b1...), Luxor.Point(b2...), :stroke)

	is = intersection(LineSegment(b1, b2), LineSegment(a1, a2))
	Luxor.sethue("blue")
	Luxor.line(Luxor.Point(is.p...), Luxor.Point(is.q...), :stroke)
end
```

which produces this image
lazysets

If I let it run with Float64 I get an empty set which works.

### PR DESCRIPTION
**Pull request by schillic**
Closes #3629.

The old code from #2138 was not correct. This PR adds a simple but non-optimized fix in the same spirit.

This works now:

```julia
LS1 = LineSegment(Float32[-34.67, -46.06], Float32[-13.03, -49.77]);
LS2 = LineSegment(Float32[-22.473152, -48.13686], Float32[-19.031397, -48.730015]);
intersection(LS1, LS2)
```

### CODE REVIEW

File: src/Sets/LineSegment/intersection.jl [hunk 1]
```diff
@@ -34,24 +34,31 @@ function intersection(LS1::LineSegment, LS2::LineSegment)
...
+                        p = v1
+                    elseif _isapprox(v1, p)
+                        return Singleton(p)
+                    else
+                        return LineSegment(p, v1)
+                    end
+                end
+            end
+        end
+        error("this should not happen")
```
Comment (Wikunia) [inline src/Sets/LineSegment/intersection.jl:59]: Would this work?
```julia
points = [LS1.p, LS1.q, LS2.p, LS2.q]
sorted_points = sort(points, by = p -> (p[1], p[2]))
mid_point1 = sorted_points[2]
mid_point2 = sorted_points[3]

if LazySets._isapprox(mid_point1, mid_point2)
    return Singleton(mid_point1)  # edges have a point in common
else
    return LineSegment(mid_point1, mid_point2)
end
```

Comment (schillic) [reply src/Sets/LineSegment/intersection.jl]: Yes, and it is much better! I just added a commit use to your implementation.

```julia
julia> @time intersection(s10, s11)  # old version
  0.000021 seconds (45 allocations: 2.672 KiB)
LineSegment{Float64, Vector{Float64}}([0.0, 1.0], [1.0, 0.0])

julia> @time intersection(s10, s11)  # new version
  0.000012 seconds (10 allocations: 480 bytes)
LineSegment{Float64, Vector{Float64}}([0.0, 1.0], [1.0, 0.0])
```

Comment (Wikunia) [reply src/Sets/LineSegment/intersection.jl]: Ah I meant only for the lines 44-59 in your previous approach. I haven't found something nicely for the empty set one yet.

Comment (schillic) [reply src/Sets/LineSegment/intersection.jl]: True. I added efficient code for the box approximation that does not allocate.

File: src/Sets/LineSegment/intersection.jl [hunk 2]
```diff
@@ -34,24 +34,34 @@ function intersection(LS1::LineSegment, LS2::LineSegment)
...
-            return Singleton([p1, p2])  # edges have a point in common
+        # line segments are on the same line
 
-        elseif _leq(p1, q1) && _leq(p2, q2)
-            return LineSegment([p1, p2], [q1, q2])
+        # check that the line segments intersect
+        @inbounds begin
+            # box approximation
+            l, r = LS1.p[1] < LS1.q[1] ? (LS1.p[1], LS1.q[1]) : (LS1.q[1], LS1.p[1])
+            b, t = LS1.p[2] < LS1.q[2] ? (LS1.p[2], LS1.q[2]) : (LS1.q[2], LS1.p[2])
```
Comment (Wikunia) [inline src/Sets/LineSegment/intersection.jl:43]: Can be shortened to:
```julia
l, r = extrema((LS1.p[1], LS1.q[1]))
b, t = extrema((LS1.p[2], LS1.q[2]))
```

Comment (schillic) [inline src/Sets/LineSegment/intersection.jl:43]:
```suggestion
            l, r = extrema((LS1.p[1], LS1.q[1]))
            b, t = extrema((LS1.p[2], LS1.q[2]))
```

File: src/Sets/LineSegment/intersection.jl [hunk 3]
```diff
@@ -34,24 +34,34 @@ function intersection(LS1::LineSegment, LS2::LineSegment)
...
+            b, t = extrema((LS1.p[2], LS1.q[2]))
+            # check that the other line segment has at least one point inside the box
+            if !(l <= LS2.p[1] <= r && b <= LS2.p[2] <= t) &&
+               !(l <= LS2.q[1] <= r && b <= LS2.q[2] <= t)
+                return EmptySet{N}(2)
+            end
+        end
 
+        # find the middle two points of the four end points
+        points = [LS1.p, LS1.q, LS2.p, LS2.q]
```
Comment (Wikunia) [inline src/Sets/LineSegment/intersection.jl:52]: One could use `SVector(LS1.p, LS1.q, LS2.p, LS2.q)` I suppose but maybe at some point one doesn't have to worry about optimization anymore 😄 as it's already much faster than the current version + the bug is fixed.

Comment (schillic) [reply src/Sets/LineSegment/intersection.jl:52]: I agree. Just to mention that my measurements were wrt. my first new version. I did not benchmark the old version, which was probably similarly efficient (but, as you say, incorrect).

Comment (Wikunia) [reply src/Sets/LineSegment/intersection.jl:52]: Actually even comparing it to the current  v2.14.1 one we got twice as fast.

```julia
julia> ls1 = LineSegment(Float32[-34.67, -46.06], Float32[-13.03, -49.77])
LineSegment{Float32, Vector{Float32}}(Float32[-34.67, -46.06], Float32[-13.03, -49.77])

julia> ls2 = LineSegment(Float32[-22.473152, -48.13686], Float32[-19.031397, -48.730015])

julia> @benchmark intersection($ls1, $ls2) # LazySets  v2.14.1
BenchmarkTools.Trial: 10000 samples with 9 evaluations.
 Range (min … max):  2.269 μs …   9.648 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     2.389 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   2.424 μs ± 208.256 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

      ▄█▇▃▁▁▂▁                                                 
  ▁▁▂▆█████████▆▄▃▃▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁ ▂
  2.27 μs         Histogram: frequency by time        3.09 μs <

 Memory estimate: 1.14 KiB, allocs estimate: 47.

julia> @benchmark new_intersection($ls1, $ls2) # with SVector
BenchmarkTools.Trial: 10000 samples with 10 evaluations.
 Range (min … max):  1.079 μs …  3.646 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     1.133 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   1.149 μs ± 86.237 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

          ▁█▁▁  ▁                                             
  ▂▂▂▃▇▇███████▇█▅▄▄▄▅▃▃▃▃▄▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▂▂ ▃
  1.08 μs        Histogram: frequency by time        1.37 μs <

 Memory estimate: 560 bytes, allocs estimate: 21.
 ```

**Review by mforets — APPROVED** [review]
