### PR TITLE
#1061 - Add linear map of empty set

### LINKED ISSUE #1061: Concrete linear map of an empty set
```julia
julia> linear_map(ones(2, 2), EmptySet())
ERROR: MethodError: no method matching linear_map(::Array{Float64,2}, ::EmptySet{Float64})
Closest candidates are:
  linear_map(::AbstractArray{N<:Real,2}, ::AbstractPolygon{N<:Real}; output_type) where N<:Real at /Users/forets/.julia/dev/LazySets/src/AbstractPolygon.jl:2
07
  linear_map(::AbstractArray{N<:Real,2}, ::ZeroSet{N<:Real}) where N<:Real at /Users/forets/.julia/dev/LazySets/src/ZeroSet.jl:178
  linear_map(::AbstractArray{N<:Real,2}, ::AbstractSingleton{N<:Real}) where N<:Real at /Users/forets/.julia/dev/LazySets/src/AbstractSingleton.jl:166

  ...
Stacktrace:
 [1] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by mforets**
Closes #1061.

### CODE REVIEW

File: src/EmptySet.jl [hunk 1]
```diff
@@ -225,3 +226,19 @@ An error.
 function diameter(S::EmptySet, p::Real=Inf)
     error("an empty set does not have a diameter")
 end
+
+"""
+    linear_map(M::AbstractMatrix{N}, ∅::EmptySet{N}) where {N}
+
+Return the linear map of an empt set
```
Comment (schillic) [inline src/EmptySet.jl]:
```suggestion
Return the linear map of an empty set.
```
