### PR TITLE
#321 - Vector-set multiplication

### LINKED ISSUE #321: Vector-set multiplication
```julia
julia> using LazySets

julia> X = Interval([0.9, 1.10445])
LazySets.Interval{Float64,IntervalArithmetic.Interval{Float64}}([0.9, 1.10445])

julia> a = [0.0029649, -0.00173048]
2-element Array{Float64,1}:
  0.0029649 
 -0.00173048

julia> a * X
ERROR: MethodError: no method matching one(::Type{Array{Float64,1}})
Closest candidates are:
  one(::BitArray{2}) at bitarray.jl:427
  one(::Type{IntervalArithmetic.Interval{T<:Real}}) where T<:Real at /Users/forets/.julia/v0.6/IntervalArithmetic/src/intervals/arithmetic.jl:57
  one(::Type{IntervalArithmetic.DecoratedInterval{T<:Real}}) where T<:Real at /Users/forets/.julia/v0.6/IntervalArithmetic/src/decorations/functions.jl:7
  ...
Stacktrace:
 [1] *(::Array{Float64,1}, ::LazySets.Interval{Float64,IntervalArithmetic.Interval{Float64}}) at /Users/forets/.julia/v0.6/LazySets/src/LinearMap.jl:76
```

### PR DESCRIPTION
**Pull request by mforets**
Closes #321.

### CODE REVIEW

File: test/unit_LinearMap.jl [hunk 1]
```diff
@@ -56,4 +56,12 @@ for N in [Float64, Rational{Int}, Float32]
     lm = N(2.) * BallInf(N[0., 0.], N(1.))
     an_element(lm)
 #     @test an_element(lm) ∈ lm # TODO results in an error for Rational
+
+    # check lineear map bewteen vector and set
```
Comment (schillic) [inline test/unit_LinearMap.jl]: "linear map between"
