### PR TITLE
#1916 - Fix crash in isequivalent for same set types

### LINKED ISSUE #1916: _isapprox method for Array{<:LazySet}
Is was trying to check if two HPolyhedron are equivalent by calling
```julia
isequivalent(HPolyhedron(rand(2,2), rand(2)), HPolyhedron(rand(2,2), rand(2)))
ERROR: MethodError: no method matching _isapprox(::Array{HalfSpace{Float64,VN} where VN<:AbstractArray{Float64,1},1}, ::Array{HalfSpace{Float64,VN} where VN<:AbstractArray{Float64,1},1})
Stacktrace:
 [1] isapprox(::HPolyhedron{Float64}, ::HPolyhedron{Float64}) at C:\Users\wueli\.julia\dev\LazySets\src\Interfaces\LazySet.jl:475
 [2] isequivalent(::HPolyhedron{Float64}, ::HPolyhedron{Float64}) at C:\Users\wueli\.julia\dev\LazySets\src\Interfaces\LazySet.jl:785
 [3] top-level scope at none:0
```

which reduceds to the following method which is not defined for `HalfSpaces`or `Array` of `HalfSpaces`
```julia 
LazySets._isapprox(HalfSpace(rand(2), rand()),HalfSpace(rand(2), rand()))  
ERROR: MethodError: no method matching _isapprox(::HalfSpace{Float64,Array{Float64,1}}, ::HalfSpace{Float64,Array{Float64,1}})
```
I am not sure if I did something wrong or if this feature is missing.

### LINKED ISSUE #2370: Fix equivalence of sets
```julia
        vars = @variables x y
        p1 = HPolyhedron([x + y <= 1, x + y >= -1,  x - y <= 1, x - y >= -1], vars)
        b1 = Ball1(zeros(2), 1.0)
        @test isequivalent(p1, b1)

        p2 = HPolyhedron([x == 0, y <= 0], vars)
        h2 = HPolyhedron([HalfSpace([1.0, 0.0], 0.0), HalfSpace([-1.0, 0.0], 0.0), HalfSpace([0.0, 1.0], 0.0)])
        @test p2 ⊆ h2 && h2 ⊆ p2 # works

       @test isequivalent(p2, h2)

julia>         @test isequivalent(p2, h2)

Error During Test at REPL[13]:1
  Test threw exception
  Expression: isequivalent(p2, h2)
  MethodError: no method matching _isapprox(::Array{HalfSpace{Float64,Array{Float64,1}},1}, ::Array{HalfSpace{Float64,Array{Float64,1}},1})
  Stacktrace:
   [1] isapprox(::HPolyhedron{Float64,Array{Float64,1}}, ::HPolyhedron{Float64,Array{Float64,1}}) at /home/mforets/.julia/dev/LazySets/src/Interfaces/LazySet.
jl:533
   [2] isequivalent(::HPolyhedron{Float64,Array{Float64,1}}, ::HPolyhedron{Float64,Array{Float64,1}}) at /home/mforets/.julia/dev/LazySets/src/Interfaces/Lazy
Set.jl:838
   [3] top-level scope at REPL[13]:1
   [4] eval(::Module, ::Any) at ./boot.jl:331
   [5] eval_user_input(::Any, ::REPL.REPLBackend) at /home/mforets/Tools/julia-1.5.0-beta1-linux-x86_64/julia-1.5.0-beta1/share/julia/stdlib/v1.5/REPL/src/REP
L.jl:134
   [6] repl_backend_loop(::REPL.REPLBackend) at /home/mforets/Tools/julia-1.5.0-beta1-linux-x86_64/julia-1.5.0-beta1/share/julia/stdlib/v1.5/REPL/src/REPL.jl:
195
   [7] start_repl_backend(::REPL.REPLBackend, ::Any) at /home/mforets/Tools/julia-1.5.0-beta1-linux-x86_64/julia-1.5.0-beta1/share/julia/stdlib/v1.5/REPL/src/
REPL.jl:180
   [8] run_repl(::REPL.AbstractREPL, ::Any; backend_on_current_task::Bool) at /home/mforets/Tools/julia-1.5.0-beta1-linux-x86_64/julia-1.5.0-beta1/share/julia
/stdlib/v1.5/REPL/src/REPL.jl:292
   [9] run_repl(::REPL.AbstractREPL, ::Any) at /home/mforets/Tools/julia-1.5.0-beta1-linux-x86_64/julia-1.5.0-beta1/share/julia/stdlib/v1.5/REPL/src/REPL.jl:2
88
   [10] (::Base.var"#802#804"{Bool,Bool,Bool,Bool})(::Module) at ./client.jl:399
   [11] #invokelatest#1 at ./essentials.jl:710 [inlined]
   [12] invokelatest at ./essentials.jl:709 [inlined]
   [13] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:383
   [14] exec_options(::Base.JLOptions) at ./client.jl:313
   [15] _start() at ./client.jl:506

ERROR: There was an error during testing
```

### PR DESCRIPTION
**Pull request by schillic**
This is a proposal to fix #1916 and fix #2370 quickly.

### CODE REVIEW

**Comment by schillic** [comment]
The build error is unrelated.

File: src/Interfaces/LazySet.jl [hunk 1]
```diff
@@ -810,9 +810,8 @@ Return whether two LazySets are equal in the mathematical sense, i.e. equivalent
 
 ## Algorithm
 
-First, the check `X == Y` is performed which returns `true` if and only if the given sets are of the same type,
-and have the same values (modulo floating-point tolerance). Otherwise, the double inclusion check `X ⊆ Y && Y ⊆ X` is
-used.
+First we check `X ≈ Y`.
```
Comment (mforets) [inline src/Interfaces/LazySet.jl:813]: can you please add a short sentence explaining what

**Review by mforets — APPROVED** [review]
the change looks good to me. i left a comment because i think it's relevant to document here how does the function behave when the sets are of the same type.
