### PR TITLE
#206 - allow arbitrary vectors for ExponentialMap's σ

### LINKED ISSUE #205: σ of ExponentialMap crashes for sparse direction vector

### LINKED ISSUE #206: Dense vector required for decompose
usage of sparse vector as the last input of `expmv` is not allwed and causes:

```julia
M = SparseMatrixExp(sprandn(10, 10, 0.5))
X = BallInf(zeros(10), 1.)
Approximations.decompose(M * X)

MethodError: no method matching expmv(::Float64, ::SparseMatrixCSC{Float64,Int64}, ::SparseVector{Float64,Int64})
Closest candidates are:
  expmv(::Number, ::Any, ::Array{T,1}; tol, m, norm) where T at /Users/forets/.julia/v0.6/Expokit/src/expmv.jl:17
```

the afffected types are `ExponentialMap` and `ExponentialProjectionMap`.

### PR DESCRIPTION
**Pull request by schillic**
Closes #206.

### CODE REVIEW

File: src/ExponentialMap.jl [hunk 1]
```diff
@@ -311,7 +311,8 @@ exponential, and ``X`` is a set, it follows that
 """
 function σ(d::AbstractVector{N},
            eprojmap::ExponentialProjectionMap)::AbstractVector{N} where {N<:Real}
-    daux = transpose(eprojmap.projspmexp.L) * d
+    d_dense = d isa Vector ? d : Vector(d)
+    daux = transpose(eprojmap.projspmexp.L) * d_dense
```
Comment (mforets) [inline src/ExponentialMap.jl]: maybe add a comment `# expmv requires a Vector`

Comment (mforets) [reply src/ExponentialMap.jl]: ah, just saw the comment in the docstring above :)

Comment (schillic) [reply src/ExponentialMap.jl]: But I forgot it in the second case 👍
