### PR TITLE
#1063 - Add intersection of linearmap

### LINKED ISSUE #1063: Intersection of LinearMap and LazySet is missing
```
ERROR: LoadError: MethodError: no method matching intersection(::LinearMap{Float64,HalfSpace{Float64},Float64,SparseArrays.SparseMatrixCSC{Float64,Int64}}, ::Hyperrectangle{Float64})
Closest candidates are:
  intersection(::AbstractHyperrectangle{N<:Real}, ::AbstractHyperrectangle{N<:Real}) where N<:Real at /Users/kpotomkin/.julia/dev/LazySets/src/concrete_intersection.jl:82
  intersection(::Union{HPolyhedron{N<:Real}, HPolytope{N<:Real}}, ::AbstractPolytope{N<:Real}; backend, prunefunc) where N<:Real at/Users/kpotomkin/.julia/dev/LazySets/src/concrete_intersection.jl:425
  intersection(::S1<:AbstractPolytope{N<:Real}, ::S2<:AbstractPolytope{N<:Real}) where {N<:Real, S1<:AbstractPolytope{N<:Real}, S2<:AbstractPolytope{N<:Real}} at /Users/kpotomkin/.julia/dev/LazySets/src/concrete_intersection.jl:462
Stacktrace:
 [1] is_intersection_empty(::LinearMap{Float64,HalfSpace{Float64},Float64,SparseArrays.SparseMatrixCSC{Float64,Int64}}, ::Hyperrectangle{Float64}, ::Bool) at /Users/kpotomkin/.julia/dev/LazySets/src/is_intersection_empty.jl:37 (repeats 2 times)
 [2] isempty(::Intersection{Float64,LinearMap{Float64,HalfSpace{Float64},Float64,SparseArrays.SparseMatrixCSC{Float64,Int64}},Hyperrectangle{Float64}}) at /Users/kpotomkin/.julia/dev/LazySets/src/Intersection.jl:515
 [3] tube⋂inv!(::LazyLowDimDiscretePost, ::Array{ReachSet{CartesianProductArray{Float64,LazySet{Float64}},Float64},1}, ::Array{ReachSet{CartesianProductArray{Float64,LazySet{Float64}},Float64},1}, ::HalfSpace{Float64}, ::Array{ReachSet{LazySet{Float64},Float64},1}, ::Array{ReachSet{LazySet{Float64},Float64},1}, ::Array{Float64,1}, ::Array{Int64,1}) at /Users/kpotomkin/.julia/dev/Reachability/src/ReachSets/DiscretePost/LazyLowDimDiscretePost.jl:72
```

To reproduce it, run Reachability(lowdim  branch) on i.e. solve_hybrid_bouncing_ball.jl with following DiscretePostOperator:
```
sol = solve(system, options, BFFPSV18(), LazyLowDimDiscretePost());
```

### PR DESCRIPTION
**Pull request by mforets**
Closes #1063.

### CODE REVIEW

File: src/concrete_intersection.jl [hunk 1]
```diff
@@ -628,3 +628,21 @@ function intersection(S::AbstractSingleton{N},
...
+
+"""
+    intersection(L::LinearMap{N}, S::LazySet{N}) where {N}
+
+Return the intersection of a lazy linear map and a convex set.
+
+### Input
+
+ - `L` -- linear map
+ - `S` -- lazy set
```
Comment (schillic) [inline src/concrete_intersection.jl]:
```suggestion
 - `S` -- convex set
```

File: test/unit_LinearMap.jl [hunk 2]
```diff
@@ -63,7 +63,7 @@ for N in [Float64, Rational{Int}, Float32]
     # isempty
     @test !isempty(lm)
 
-    # an_element function
+    # an_element functionintersection
```
Comment (schillic) [inline test/unit_LinearMap.jl]: ?

**Comment by schillic** [comment]
I just realized that the symmetric method is missing.
