### PR TITLE
#1201 - Add a dimension to EmptySet

### LINKED ISSUE #1201: Add a dimension to EmptySet
Computations with `EmptySet` may fail because the dimensions do not match (see for example #1097). Another example is that one cannot construct a `Universe` as the complement of an `EmptySet` because one cannot access the dimension (see #1152).
I say that we add a field for the dimension, as we did for `Universe`.

### PR DESCRIPTION
**Pull request by schillic**
Closes #1201.

The only non-trivial change is:
Since `EmptySet` now requires the dimension as input, I changed
`∅ = EmptySet{Float64}()`
to
`∅ = EmptySet{Float64}`
(i.e., you need to say `∅(k)` etc. to create an `EmptySet` of dimension `k`).

### CODE REVIEW

File: src/Sets/EmptySet.jl [hunk 1]
```diff
@@ -142,7 +143,7 @@ The output is always `false`.
 ### Examples
 
 ```jldoctest
-julia> [1.0, 0.0] ∈ ∅
+julia> [1.0, 0.0] ∈ EmptySet(2)
```
Comment (mforets) [inline src/Sets/EmptySet.jl]:
```suggestion
julia> [1.0, 0.0] ∈ ∅(2)
```
