### PR TITLE
Conversions to CP and CPA

### LINKED ISSUE #1319: Convert 2D hyperrectangle to the cartesian product of intervals
MWE:

```julia
julia> H = Hyperrectangle([0.0, 0.0], [1.0, 1.0]);

julia> Hcp = convert(CartesianProduct{Float64, Interval{Float64}, Interval{Float64}}, H)

MethodError: Cannot `convert` an object of type Hyperrectangle{Float64} to an object of type CartesianProduct{Float64,Interval{Float64,IN} where IN<:IntervalArithmetic.AbstractInterval{Float64},Interval{Float64,IN} where IN<:IntervalArithmetic.AbstractInterval{Float64}}
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T at essentials.jl:154
  CartesianProduct{Float64,Interval{Float64,IN} where IN<:IntervalArithmetic.AbstractInterval{Float64},Interval{Float64,IN} where IN<:IntervalArithmetic.AbstractInterval{Float64}}(::Any, !Matched::Any) where {N<:Real, S1<:LazySet{N<:Real}, S2<:LazySet{N<:Real}} at /Users/forets/.julia/dev/LazySets/src/CartesianProduct.jl:35

Stacktrace:
 [1] top-level scope at In[20]:1
```

Proposal:

```julia
# convert a two-dimensional hyperrectangle to the cartesian product of two intervals
function convert(::Type{CartesianProduct{N, Interval{N}, Interval{N}}}, H::AbstractHyperrectangle{N}) where {N<:Real}
    @assert dim(H) == 2 "hyperrectangle must be two-dimensional for conversion into "
            " the cartesian product of intervals, but it is $(dim(H))-dimensional"
    low_H = low(H)
    high_H = high(H)
    return CartesianProduct(Interval(low_H[1], high_H[1]), Interval(low_H[2], high_H[2]))
end
```

Application:

```julia
julia> Hcp = convert(CartesianProduct{Float64, Interval{Float64}, Interval{Float64}}, H)

CartesianProduct{Float64,Interval{Float64,IntervalArithmetic.Interval{Float64}},Interval{Float64,IntervalArithmetic.Interval{Float64}}}(Interval{Float64,IntervalArithmetic.Interval{Float64}}([-1, 1]), Interval{Float64,IntervalArithmetic.Interval{Float64}}([-1, 1]))
```

### LINKED ISSUE #1335: Convert nD hyperrectangle to the cartesian product array of intervals
Extension of https://github.com/JuliaReach/LazySets.jl/issues/1319.

```julia
julia> H = Hyperrectangle([0.0, 0.0, 0.0], [1.0, 1.0, 1.0]);

julia> Hcp = convert(CartesianProduct{Float64, Interval{Float64})

ERROR: MethodError: Cannot `convert` an object of type Hyperrectangle{Float64} to an object of type CartesianProductArray{Float64,Interval{Float64,IN} where IN
<:IntervalArithmetic.AbstractInterval{Float64}}
```

### PR DESCRIPTION
**Pull request by mforets**
Closes #1319.
Closes #1335.

### CODE REVIEW

File: test/unit_CartesianProduct.jl [hunk 1]
```diff
@@ -141,6 +145,13 @@ for N in [Float64, Float32, Rational{Int}]
     H = convert(Hyperrectangle, b1 × h2)
     @test low(H) == N[0, 2, 4] && high(H) == N[1, 3, 5]
 
+    # convert a hyperrectangle to a cartesian product of intervals
+    H = Hyperrectangle(N[0, 0], N[1, 1])
+    Hcp = convert(CartesianProduct{N, Interval{N}, Interval{N}}, H)
+    @test Hcp isa CartesianProduct &&
+          Hcp.X == Interval(N(-1), N(1)) &&
+          Hcp.Y == Interval(N(-1), N(1))
```
Comment (schillic) [inline test/unit_CartesianProduct.jl]: Can we have different entries to test that the order is correct?
`H = Hyperrectangle(N[0, 1], N[1, 3])` and then `Hcp.X == Interval(N(-1), N(1)) && Hcp.Y == Interval(N(-2), N(4))`

File: test/unit_CartesianProduct.jl [hunk 2]
```diff
@@ -227,6 +242,13 @@ for N in [Float64, Float32, Rational{Int}]
     res, w = ⊆(cpa2, cpa1, true)
     @test !⊆(cpa2, cpa1) && !res && w ∈ cpa2 && w ∉ cpa1
 
+    # convert a hyperrectangle to the cartesian product array of intervals
+    # convert a hyperrectangle to a cartesian product of intervals
+    H = Hyperrectangle(N[0, 0, 0], N[1, 1, 1])
+    Hcp = convert(CartesianProductArray{N, Interval{N}}, H)
+    @test Hcp isa CartesianProductArray &&
+          all([Hcpi == Interval(N(-1), N(1)) for Hcpi in array(Hcp)])
```
Comment (schillic) [inline test/unit_CartesianProduct.jl]: Same as above.
`H = Hyperrectangle(N[0, 1, 2], N[1, 2, 3])` and then `all([array(Hcp)[i] == Interval(N(-1), N(2*i+1)) for i in 1:3])`

File: src/convert.jl [hunk 3]
```diff
@@ -612,6 +612,52 @@ function convert(::Type{Hyperrectangle},
...
+- `H`                -- hyperrectangle
+
+### Output
+
+The cartesian product of two intervals.
+"""
+function convert(::Type{CartesianProduct{N, Interval{N}, Interval{N}}},
+                 H::AbstractHyperrectangle{N}) where {N<:Real}
+    @assert dim(H) == 2 "the hyperrectangle must be two-dimensional to convert it to "
+            "the cartesian product of intervals, but it is $(dim(H))-dimensional"
```
Comment (schillic) [inline src/convert.jl]:
```suggestion
            "the cartesian product of two intervals, but it is $(dim(H))-dimensional"
```
Maybe point to `CartesianProductArray` here: `consider converting to 'CartesianProductArray' instead`
