### PR TITLE
#2447 - Fix plot for SArray inputs

### LINKED ISSUE #2447: Plotting zonotope with SArray fields fails
... I thought this was fixed :open_mouth: 

```julia
julia> using LazySets, StaticArrays, Plots

julia> Z = Zonotope(SA[1.0, 0.0], SA[1.0 0.0; 0.0 1.0]) ;

julia> vertices_list(Z)
4-element Array{SArray{Tuple{2},Float64,1,2},1}:
 [2.0, 1.0]
 [0.0, 1.0]
 [0.0, -1.0]
 [2.0, -1.0]

julia> plot(Z)
ERROR: MethodError: no method matching resize!(::SArray{Tuple{4},Float64,1,4}, ::Int64)
Closest candidates are:
  resize!(::Array{T,1} where T, ::Integer) at array.jl:1082
  resize!(::BitArray{1}, ::Integer) at bitarray.jl:799
  resize!(::MathOptInterface.Utilities.CleverDicts.CleverDict{K,V,F,I} where I<:Function where F<:Function, ::Any) where {K, V} at /home/mforets/.julia/packages/MathOptInterface/ZJFKw/src/Utilities/CleverDicts.jl:344
  ...
Stacktrace:
 [1] _append!(::SArray{Tuple{4},Float64,1,4}, ::Base.HasLength, ::Tuple{Float64}) at ./array.jl:987
 [2] append!(::SArray{Tuple{4},Float64,1,4}, ::Tuple{Float64}) at ./array.jl:981
 [3] push!(::SArray{Tuple{4},Float64,1,4}, ::Float64) at ./array.jl:982
 [4] plot_recipe(::Zonotope{Float64,SArray{Tuple{2},Float64,1,2},SArray{Tuple{2,2},Float64,2,4}}, ::Float64) at /home/mforets/.julia/dev/LazySets/src/Interfaces/AbstractPolyhedron_functions.jl:804
 [5] macro expansion at /home/mforets/.julia/dev/LazySets/src/Plotting/plot_recipes.jl:258 [inlined]
 [6] apply_recipe(::AbstractDict{Symbol,Any}, ::Zonotope{Float64,SArray{Tuple{2},Float64,1,2},SArray{Tuple{2,2},Float64,2,4}}, ::Float64) at /home/mforets/.julia/packages/RecipesBase/92zOw/src/RecipesBase.jl:282
 [7] apply_recipe(::AbstractDict{Symbol,Any}, ::Zonotope{Float64,SArray{Tuple{2},Float64,1,2},SArray{Tuple{2,2},Float64,2,4}}) at /home/mforets/.julia/packages/RecipesBase/92zOw/src/RecipesBase.jl:276
 [8] _process_userrecipes!(::Any, ::Any, ::Any) at /home/mforets/.julia/packages/RecipesPipeline/uPBKQ/src/user_recipe.jl:36
 [9] recipe_pipeline!(::Any, ::Any, ::Any) at /home/mforets/.julia/packages/RecipesPipeline/uPBKQ/src/RecipesPipeline.jl:70
 [10] _plot!(::Plots.Plot, ::Any, ::Any) at /home/mforets/.julia/packages/Plots/vsE7b/src/plot.jl:172
 [11] #plot#129 at /home/mforets/.julia/packages/Plots/vsE7b/src/plot.jl:58 [inlined]
 [12] plot(::Any) at /home/mforets/.julia/packages/Plots/vsE7b/src/plot.jl:52
 [13] top-level scope at REPL[4]:1

```

### PR DESCRIPTION
**Pull request by mforets**
Closes #2447.

### CODE REVIEW

File: src/Interfaces/AbstractPolyhedron_functions.jl [hunk 1]
```diff
@@ -773,7 +773,8 @@ Convert a (bounded) polyhedron to a pair `(x, y)` of points for plotting.
 
 ### Output
 
-A pair `(x, y)` of points that can be plotted.
+A pair `(x, y)` of points that can be plotted, where `x` is the vector of x-coordinates
+and `y` is a vector of `y` is the vector of y-coordinates.
```
Comment (schillic) [inline src/Interfaces/AbstractPolyhedron_functions.jl:777]:
```suggestion
and `y` is the vector of y-coordinates.
```

**Review by schillic — APPROVED** [review]
