### PR TITLE
#2386 - Use approximate equality check in samedir

### LINKED ISSUE #2386: "AssertionError: the constraints must have the same normal direction"  after  passed "samedir" check.
```julia
HPolytope{Float64,Array{Float64,1}}(HalfSpace{Float64,Array{Float64,1}}[HalfSpace{Float64,Array{Float64,1}}([1.0, 0.0], 1.0), HalfSpace{Float64,Array{Float64,1}}([0.0, 1.0], 1.0), HalfSpace{Float64,Array{Float64,1}}([-1.0, 0.0], 1.0), HalfSpace{Float64,Array{Float64,1}}([0.0, -1.0], 1.0), HalfSpace{Float64,Array{Float64,1}}([0.17178027783046604, -0.342877222169534], -0.3988040749330524), HalfSpace{Float64,Array{Float64,1}}([0.17228094170254737, -0.3438765582974526], -0.5161575)])

AssertionError: the constraints must have the same normal direction

Stacktrace:
 [1] macro expansion at /home/wth/.julia/packages/LazySets/FwmiZ/src/Assertions/Assertions.jl:23 [inlined]
 [2] is_tighter_same_dir_2D(::HalfSpace{Float64,Array{Float64,1}}, ::HalfSpace{Float64,Array{Float64,1}}; strict::Bool) at /home/wth/.julia/packages/LazySets/FwmiZ/src/Sets/HalfSpace.jl:460
 [3] isredundant(::HalfSpace{Float64,Array{Float64,1}}, ::HalfSpace{Float64,Array{Float64,1}}, ::HalfSpace{Float64,Array{Float64,1}}) at /home/wth/.julia/packages/LazySets/FwmiZ/src/Interfaces/AbstractHPolygon.jl:348
 [4] addconstraint!(::Array{HalfSpace{Float64,Array{Float64,1}},1}, ::HalfSpace{Float64,Array{Float64,1}}; linear_search::Bool, prune::Bool) at /home/wth/.julia/packages/LazySets/FwmiZ/src/Interfaces/AbstractHPolygon.jl:521
 [5] #addconstraint!#72 at /home/wth/.julia/packages/LazySets/FwmiZ/src/Interfaces/AbstractHPolygon.jl:434 [inlined]
 [6] convert(::Type{HPolygon}, ::HPolytope{Float64,Array{Float64,1}}; prune::Bool) at /home/wth/.julia/packages/LazySets/FwmiZ/src/convert.jl:239
 [7] vertices_list(::HPolytope{Float64,Array{Float64,1}}; backend::Nothing, prune::Bool) at /home/wth/.julia/packages/LazySets/FwmiZ/src/Sets/HPolytope.jl:218
 [8] vertices_list at /home/wth/.julia/packages/LazySets/FwmiZ/src/Sets/HPolytope.jl:213 [inlined]
 [9] area(::HPolytope{Float64,Array{Float64,1}}) at /home/wth/.julia/packages/LazySets/FwmiZ/src/Interfaces/LazySet.jl:944
 [10] ordinal_split!(::IntervalNet, ::Problem{HPolytope{Float64,Array{Float64,1}},HPolytope{Float64,Array{Float64,1}}}, ::NeuralVerification.Tree{Tuple{HPolytope{Float64,Array{Float64,1}},Array{Any,1}}}, ::Int64, ::Int64, ::Array{Tuple{Int64,Int64},1}) at /home/wth/dev/NeuralVerification.jl/src/runtime/trainingVerification.jl:59
 [11] init_split at /home/wth/dev/NeuralVerification.jl/src/runtime/trainingVerification.jl:91 [inlined]
 [12] solve(::TrainingProblem{HPolytope{Float64,Array{Float64,1}},HPolytope{Float64,Array{Float64,1}}}, ::Int64, ::Bool, ::Bool, ::Float64, ::Bool) at /home/wth/dev/NeuralVerification.jl/src/runtime/trainingVerification.jl:320
 [13] macro expansion at ./timing.jl:310 [inlined]
 [14] test2D(::String, ::Int64, ::Bool, ::Bool, ::Float64, ::Bool) at ./In[3]:42
 [15] test2D(::String, ::Int64, ::Bool, ::Bool, ::Float64) at ./In[3]:28
 [16] top-level scope at In[20]:1
 [17] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1091
```

### PR DESCRIPTION
**Pull request by schillic**
Closes #2386.

### CODE REVIEW

File: src/Arrays/vector_operations.jl [hunk 1]
```diff
@@ -111,7 +111,7 @@ function samedir(u::AbstractVector{N},
             if factor < 0
                 return (false, 0)
             end
-        elseif factor != u[i] / v[i]
+        elseif !isapproxzero(factor - u[i] / v[i])
```
Comment (mforets) [inline src/Arrays/vector_operations.jl:114]:
```suggestion
        elseif !_isapprox(factor, u[i] / v[i])
```
(the code for `_isapprox` uses both `isapproxzero` and also relative tolerances.. should be safer..)

File: test/unit_Polygon.jl [hunk 2]
```diff
@@ -540,6 +540,15 @@ for N in [Float64]
...
     @test ispermutation(P.constraints, Hs[3:6])
+
+    # redundancy with almost-parallel constraints and approximation issues (#2386)
+    HPolygon([HalfSpace([1.0, 0.0], 1.0),
+              HalfSpace([0.0, 1.0], 1.0),
+              HalfSpace([-1.0, 0.0], 1.0),
+              HalfSpace([0.0, -1.0], 1.0),
+              HalfSpace([0.17178027783046604, -0.342877222169534], -0.3988040749330524),
+              HalfSpace([0.17228094170254737, -0.3438765582974526], -0.5161575)
+             ])
```
Comment (mforets) [inline test/unit_Polygon.jl:551]: we can add that `vertices_list(P) ≈ [[-1.0, 1.0]]`.

Comment (schillic) [reply test/unit_Polygon.jl]: In fact we can use equality :+1:

**Review by mforets — APPROVED** [review]
