### PR TITLE
Various docs fixes

### LINKED ISSUE #329: Fix deprecations for concrete polyhedra doctests
See https://juliareach.github.io/LazySets.jl/latest/man/concrete_polyhedra.html

### PR DESCRIPTION
**Pull request by mforets**
Closes #329.

### CODE REVIEW

File: src/HPolytope.jl [hunk 1]
```diff
@@ -218,8 +218,8 @@ export intersect, convex_hull, cartesian_product, vertices_list
 # NOTE: alternatively take SimpleHRepresentation(hrep(P)) fields A and b
```
Comment (schillic) [inline src/HPolytope.jl]: Should we remove this comment?
