### PR TITLE
#1231 - Convert lazy linear map of hyperrectangular set to zonotope

### LINKED ISSUE #1231: Convert lazy linear map of hyperrectangular set to a zonotope
```julia
julia> convert(Zonotope, rand(2,2)*rand(BallInf))
ERROR: MethodError: Cannot `convert` an object of type LinearMap{Float64,BallInf{Float64},Float64,Array{Float64,2}} to an object of type Zonotope
Closest candidates are:
  convert(::Type{Zonotope}, ::AbstractHyperrectangle) at /Users/forets/.julia/dev/LazySets/src/convert.jl:256
  convert(::Type{Zonotope}, ::CartesianProduct{N<:Real,Zonotope{N<:Real},Zonotope{N<:Real}}) where N<:Real at /Users/forets/.julia/dev/LazySets/src/convert.jl:558
  convert(::Type{Zonotope}, ::CartesianProduct{N<:Real,HN1<:AbstractHyperrectangle{N<:Real},HN2<:AbstractHyperrectangle{N<:Real}}) where {N<:Real, HN1<:AbstractH
yperrectangle{N<:Real}, HN2<:AbstractHyperrectangle{N<:Real}} at /Users/forets/.julia/dev/LazySets/src/convert.jl:278
  ...
Stacktrace:
 [1] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by mforets**
Closes #1231.

### CODE REVIEW

File: src/convert.jl [hunk 1]
```diff
@@ -303,6 +303,34 @@ function convert(::Type{Zonotope}, cpa::CartesianProductArray{N, HN}
...
+
+A zonotope.
+
+### Algorithm
+
+This method first converts the hyperrectangular set to a zonotope, and then
+applies the (concrete) linear map to the zonotope.
+"""
+function convert(::Type{Zonotope},
+                 S::LinearMap{N, SN, NM, MAT}
```
Comment (schillic) [inline src/convert.jl]: You can omit `NM` and `MAT` if you do not need them.
