### PR TITLE
#3844 - Make `box_approximation` of polyhedral `Intersection`s precise and work

### LINKED ISSUE #3844: `box_approximation` over `interection(<unbounded set>, ::AbstractPolytope)` throws assertion error
If computing say `box_approximation((Hyperrectangle(;low=[19.5], high=[20.5]) × Universe(1)) ∩ Hyperrectangle(;low=[19.5, 19.0], high=[20.5, 22.0]))` (not the most interesting example, I know, but I ran into it with this where I have no control over the LHS of the intersection) then LazySets throws the assertion error: "AssertionError: the first set in the intersection must be bounded". The box approximation over this intersection is however well-defined. The order does not matter due to `swap` in `ρ` for `Intersection`s. 

The same thing happens for the following example:
```
box_approximation(Hyperrectangle(;
        low=[-12.0, -12.0, -0.5, -2.5, -0.35, -0.5, -0.05],
        high=[12.0, 12.0, 0.5, 2.5, 0.35, 0.5, 0.05],
    ) ∩ HalfSpace([0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0], 0.1))
```

### PR DESCRIPTION
**Pull request by schillic**
Closes #3844.

### CODE REVIEW

File: src/Approximations/box_approximation.jl [hunk 1]
```diff
@@ -73,6 +77,19 @@ function box_approximation(S::LazySet{N}) where {N}
     return Hyperrectangle(c, r)
 end
 
+function box_approximation(cap::Intersection{N,T1,T2}) where {N,T1,T2}
+    if ispolyhedral(cap.X) && ispolyhedral(cap.Y)
```
Comment (Zinoex) [inline src/Approximations/box_approximation.jl:81]: I think this should be `||`. If any of the two are bounded, then the result is bounded.

**Review by mforets — APPROVED** [review]
