### PR TITLE
#2103 - Fix vertices_list for empty HPolygon

### LINKED ISSUE #2103: vertices_list of empty HPolygon crashes
```julia
julia> P = HPolygon([HalfSpace([1., 0.], 0.), HalfSpace([-1., 0.], -1.)]);

julia> isempty(P)
ERROR: MethodError: no method matching element(::EmptySet{Float64})
Closest candidates are:
  element(::Singleton{N<:Real,VN} where VN<:AbstractArray{N<:Real,1}) where N<:Real at /.julia/dev/LazySets/src/Sets/Singleton.jl:38
  element(::Singleton{N<:Real,VN} where VN<:AbstractArray{N<:Real,1}, ::Int64) where N<:Real at /.julia/dev/LazySets/src/Sets/Singleton.jl:56
  element(::ZeroSet{N<:Real}) where N<:Real at /.julia/dev/LazySets/src/Sets/ZeroSet.jl:44
  ...
Stacktrace:
 [1] #vertices_list#64(::Bool, ::Bool, ::typeof(vertices_list), ::HPolygon{Float64,Array{Float64,1}}) at /.julia/dev/LazySets/src/Interfaces/AbstractHPolygon.jl:126
 [2] vertices_list at /.julia/dev/LazySets/src/Interfaces/AbstractHPolygon.jl:120 [inlined]
 [3] isempty(::HPolygon{Float64,Array{Float64,1}}) at /.julia/dev/LazySets/src/Interfaces/AbstractPolytope.jl:95
 [4] top-level scope at REPL[38]:1
 [5] eval(::Module, ::Any) at ./boot.jl:330
 [6] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:86
 [7] run_backend(::REPL.REPLBackend) at /.julia/packages/Revise/Pcs5V/src/Revise.jl:1073
 [8] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by schillic**
Closes #2103.

### CODE REVIEW

File: test/unit_Polygon.jl [hunk 1]
```diff
@@ -236,7 +236,9 @@ for N in [Float64, Float32, Rational{Int}]
 
     # check that empty polygon (infeasible constraints) has no vertices (#918)
     P = HPolygon([HalfSpace(N[1, 1], N(0)), HalfSpace(N[-1, 0], N(-1)),
-        HalfSpace(N[0, -1], N(-1))])
+                  HalfSpace(N[0, -1], N(-1))])
+    @test vertices_list(P) == Vector{Vector{N}}()
+    P = HPolygon([HalfSpace(N[1, 0], N(0)), HalfSpace(N[-1, 0], N(-1))])
```
Comment (mforets) [inline test/unit_Polygon.jl:241]: can you add `isempty(P)` as a test?

Comment (schillic) [reply test/unit_Polygon.jl:241]: There is already such a test for an empty polygon. Since the result is an empty `Vector`, it will work (I tried).

File: src/Interfaces/AbstractHPolygon.jl [hunk 2]
```diff
@@ -123,11 +123,19 @@ function vertices_list(P::AbstractHPolygon{N};
         return points
     end
     @inbounds for i in 1:n-1
-        points[i] = element(intersection(Line(P.constraints[i]),
-                                         Line(P.constraints[i+1])))
+        cap = intersection(Line(P.constraints[i]), Line(P.constraints[i+1]))
```
Comment (mforets) [inline src/Interfaces/AbstractHPolygon.jl:126]: i presume this is not the best implementation in terms of efficiency; i would not pass through `EmptySet` and check the det condition directly. we can of course revisit this later, it's just a comment. the new function is already a step forward.

File: test/unit_Polygon.jl (hunk 1 above)
Comment (mforets) [reply test/unit_Polygon.jl:241]: ok. i would add it because that the test in your linked issue.

File: src/Interfaces/AbstractHPolygon.jl (hunk 2 above)
Comment (schillic) [reply src/Interfaces/AbstractHPolygon.jl:126]: Yes, this PR only intends to fix a bug.

File: test/unit_Polygon.jl (hunk 1 above)
Comment (schillic) [reply test/unit_Polygon.jl:241]: I added it.
