### PR TITLE
#1813 - Methods for lazy convex hull array of singleton

### LINKED ISSUE #1813: Methods for lazy convex hull of singletons
Let

```julia
a = Singleton([-1.0, 0.0])
b = Singleton([1.0, 0.0])
c = Singleton([0.0, 1.0])
Δ = ConvexHullArray([a, b, c])
```

```julia
julia> overapproximate(Δ, Hyperrectangle) ⊆ Δ

MethodError: no method matching iterate(::ConvexHullArray{Float64,Singleton{Float64,Array{Float64,1}}})
Closest candidates are:
  iterate(!Matched::Core.SimpleVector) at essentials.jl:604
  iterate(!Matched::Core.SimpleVector, !Matched::Any) at essentials.jl:604
  iterate(!Matched::ExponentialBackOff) at error.jl:214
  ...

Stacktrace:
 [1] in(::Array{Float64,1}, ::ConvexHullArray{Float64,Singleton{Float64,Array{Float64,1}}}) at ./operators.jl:1055
 [2] ∉(::Array{Float64,1}, ::ConvexHullArray{Float64,Singleton{Float64,Array{Float64,1}}}) at ./operators.jl:1068
 [3] _issubset_vertices_list(::Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}, ::ConvexHullArray{Float64,Singleton{Float64,Array{Float64,1}}}, ::Bool) at /home/mforets/.julia/dev/LazySets/src/ConcreteOperations/issubset.jl:246
 [4] #⊆#257 at /home/mforets/.julia/dev/LazySets/src/ConcreteOperations/issubset.jl:229 [inlined]
 [5] issubset(::Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}, ::ConvexHullArray{Float64,Singleton{Float64,Array{Float64,1}}}, ::Bool) at /home/mforets/.julia/dev/LazySets/src/ConcreteOperations/issubset.jl:224 (repeats 2 times)
 [6] top-level scope at In[126]:1
```

```julia
julia> constraints_list(Δ)

MethodError: no method matching constraints_list(::ConvexHullArray{Float64,Singleton{Float64,Array{Float64,1}}})
Closest candidates are:
  constraints_list(!Matched::HalfSpace{N<:Real,VN} where VN<:AbstractArray{N<:Real,1}) where N<:Real at /home/mforets/.julia/dev/LazySets/src/Sets/HalfSpace.jl:278
  constraints_list(!Matched::AbstractArray{N<:Real,2}, !Matched::AbstractArray{N<:Real,1}) where N<:Real at /home/mforets/.julia/dev/LazySets/src/Sets/HalfSpace.jl:297
  constraints_list(!Matched::AbstractHyperrectangle{N<:Real}) where N<:Real at /home/mforets/.julia/dev/LazySets/src/Interfaces/AbstractHyperrectangle.jl:239
  ...

Stacktrace:
 [1] top-level scope at In[128]:1

```

```julia
julia> vertices_list(Δ)

MethodError: no method matching vertices_list(::ConvexHullArray{Float64,Singleton{Float64,Array{Float64,1}}})
Closest candidates are:
  vertices_list(!Matched::AbstractSingleton{N<:Real}) where N<:Real at /home/mforets/.julia/dev/LazySets/src/Interfaces/AbstractSingleton.jl:255
  vertices_list(!Matched::Interval{N<:Real,IN} where IN<:IntervalArithmetic.AbstractInterval{N<:Real}) where N<:Real at /home/mforets/.julia/dev/LazySets/src/Sets/Interval.jl:407
  vertices_list(!Matched::AbstractHyperrectangle{N<:Real}) where N<:Real at /home/mforets/.julia/dev/LazySets/src/Interfaces/AbstractHyperrectangle.jl:184
  ...

Stacktrace:
 [1] top-level scope at In[127]:1
```

### PR DESCRIPTION
**Pull request by mforets**
Closes #1813.

### CODE REVIEW

File: src/Sets/VPolygon.jl [hunk 1]
```diff
@@ -197,7 +197,7 @@ function tohrep(P::VPolygon{N}, ::Type{HPOLYGON}=HPolygon
         upper_hull = [halfspace_left(vl[j], vl[j+1]) for j in i:length(vl)-1]
         mid_hull = [halfspace_left(vl[end], vl[1])]
         lower_hull = [halfspace_left(vl[j], vl[j+1]) for j in 1:i-1]
-        constraints_list = vcat(upper_hull, mid_hull, lower_hull)
+        constraints_list = vcat(upper_hull, mid_hull, lower_hull)
```
Comment (schillic) [inline src/Sets/VPolygon.jl]:
```suggestion
        constraints_list = vcat(upper_hull, mid_hull, lower_hull)
```

File: src/LazyOperations/ConvexHull.jl [hunk 2]
```diff
@@ -380,3 +380,19 @@ function vertices_list(X::ConvexHullArray{N, Singleton{N, VT}}) where {N, VT}
     end
     return vertices
 end
+
+# lis of constraints of the convex hull array of singletons
```
Comment (schillic) [inline src/LazyOperations/ConvexHull.jl]:
```suggestion
# list of constraints of the convex hull array of singletons
```

**Comment by mforets** [comment]
> Can you add tests?

Sure, i can add those from [this post](https://github.com/JuliaReach/LazySets.jl/issues/1813#issue-532430367). Also, if you want to add more tests feel free to commit on top of this branch.
