### PR TITLE
#2550 - Fix special case for VPolygon msum

### LINKED ISSUE #2550: Bug in VPolygon concrete minkowski sum with singletons
```julia
x = convert(VPolygon, Singleton([1.0, 1.0]))
y = convert(VPolygon, Hyperrectangle(low=[0.9, 2.0], high=[1.1, 2.2]))

plot(x)
plot!(y)

plot!(minkowski_sum(x, y))
```
Screenshot from 2021-02-08 14-02-35

correct:

```julia
x = Singleton([1.0, 1.0])
y = Hyperrectangle(low=[0.9, 2.0], high=[1.1, 2.2])

plot!(minkowski_sum(x, y))
````

Screenshot from 2021-02-08 14-03-00

---

the problem is in `_minkowski_sum_vrep_2d` for the special case when one of the polygons has only one vertex.

### PR DESCRIPTION
**Pull request by mforets**
Closes #2550.

jointly with @SebastianGuadalupe

### CODE REVIEW

File: src/ConcreteOperations/minkowski_sum.jl [hunk 1]
```diff
@@ -359,6 +362,29 @@ function _minkowski_sum_vrep_2d(vlistP::Vector{VT},
...
 
+# assume that at least one of the arguments has length 1
+function _minkowski_sum_vrep_2d_singleton(vlistP::Vector{VT},
+                                          vlistQ::Vector{VT}) where {N, VT<:AbstractVector{N}}
+    mP = length(vlistP)
+    mQ = length(vlistQ)
+
+    if min(mP, mQ) != 1
+        throw(ArgumentError("expected one argument to have only one vertex, got $mP and $mQ respectively"))
+    elseif mQ == 1
```
Comment (schillic) [inline src/ConcreteOperations/minkowski_sum.jl:373]:
```suggestion
    elseif mP != 1
```
Otherwise you get nontermination if `mP == mQ == 1`.

File: test/unit_Polygon.jl [hunk 2]
```diff
@@ -505,6 +505,14 @@ for N in [Float64, Float32]
...
     addconstraint!(p2, p2.constraints[2])
     @test length(p2.constraints) == 6
+
+    # test that concrete minkowski sum of a singleton and a polygon works
+    x = VPolygon([N[1, 1]])
+    y = VPolygon([N[1.1, 2.2], N[0.9, 2.2], N[0.9, 2.0], N[1.1, 2.0]])
+    v = minkowski_sum(x, y)
+
+    a = VPolygon([N[2.1, 3.2], N[1.9, 3.2], N[1.9, 3.0], N[2.1, 3.0]])
+    @test v == a
```
Comment (schillic) [inline test/unit_Polygon.jl:515]: Can you add the test case:
```suggestion
    @test v == a
    x = VPolygon([N[1, 1]])
    y = VPolygon([N[2, 1]])
    @test minkowski_sum(x, y) == VPolygon([N[3, 2]])
```

File: src/ConcreteOperations/minkowski_sum.jl (hunk 1 above)
Comment (mforets) [reply src/ConcreteOperations/minkowski_sum.jl]: good catch!

**Review by schillic — APPROVED** [review]
