### PR TITLE
#918 - vertices_list for AbstractHPolygon with infeasible constraints is incorrect

### LINKED ISSUE #918: vertices_list for AbstractHPolygon with infeasible constraints is incorrect
`vertices_list` does not work correctly if the constraints are infeasible.
The result should be an empty list, but it is not.
```julia
julia> P = HPolygon([
    HalfSpace([1.0, 1.0], 0.0),
    HalfSpace([-1.0, 0.0], -1.0),
    HalfSpace([0.0, -1.0], -1.0)]);

julia> vertices_list(P)
3-element Array{Array{Float64,1},1}:
 [1.0, -1.0]
 [1.0, 1.0] 
 [-1.0, 1.0]
```
The reason is that we take the intersection of lines without caring for the direction of the normal vector.
This has serious consequences because the emptiness check relies on it.

### PR DESCRIPTION
**Pull request by schillic**
Closes #918.

### CODE REVIEW

File: src/AbstractHPolygon.jl [hunk 1]
```diff
@@ -109,6 +123,15 @@ function vertices_list(P::AbstractHPolygon{N},
     end
     points[n] = element(intersection(Line(P.constraints[n]),
                                      Line(P.constraints[1])))
+
+    # check if polygon was empty
```
Comment (mforets) [inline src/AbstractHPolygon.jl]: did you forget to use the flag `check_feasibility`  below?

File: src/AbstractHPolygon.jl [hunk 2]
```diff
@@ -109,6 +123,15 @@ function vertices_list(P::AbstractHPolygon{N},
...
+    avg = sum(points) / length(points)
+    for c in constraints_list(P)
```
Comment (mforets) [inline src/AbstractHPolygon.jl]: note that one could ask for (see [this function](https://github.com/JuliaReach/LazySets.jl/blob/51c891e09cebdc24dfe0ac0ff604ca31a5fc1561/src/AbstractHPolygon.jl#L175)):

```julia
if avg ∉ P
    return Vector{Vector{N}}(undef, 0)
end
```

**Comment by schillic** [comment]
Thanks, I rebased.
