### PR TITLE
#746 - Wrong support vector of HalfSpace in opposite direction of normal vector

### LINKED ISSUE #746: Wrong support vector of HalfSpace in opposite direction of normal vector
```julia
julia> ρ([-1.], LazySets.HalfSpace([1.0], 1.0))
-1.0
```

### PR DESCRIPTION
**Pull request by schillic**
Closes #746.

### CODE REVIEW

File: src/Hyperplane.jl [hunk 1]
```diff
@@ -167,6 +170,9 @@ Otherwise this function throws an error.
                 elseif first_nonzero_entry_a == -1
                     factor = hp.a[i] / d[i]
                     first_nonzero_entry_a = i
+                    if halfspace && factor < 0
```
Comment (mforets) [inline src/Hyperplane.jl]: Given `N` why not returning `convert(N, Inf)`?

Comment (schillic) [reply src/Hyperplane.jl]: I created #750. To keep things consistent, let us do that change in one go.
