### PR TITLE
#599 - Set membership for VPolytope

### LINKED ISSUE #599: Set membership for VPolytope
```julia
julia> [1.0, 2.0] ∈ VPolytope([[1.0, 2.0]])
ERROR: MethodError: no method matching start(::LazySets.VPolytope{Float64})
Closest candidates are:
  start(::SimpleVector) at essentials.jl:258
  start(::Base.MethodList) at reflection.jl:560
  start(::ExponentialBackOff) at error.jl:107
  ...
Stacktrace:
 [1] any(::Base.##138#139{Array{Float64,1}}, ::LazySets.VPolytope{Float64}) at ./reduce.jl:573
 [2] in(::Array{Float64,1}, ::LazySets.VPolytope{Float64}) at ./reduce.jl:631
```

See:

https://mathoverflow.net/questions/142418/point-in-polytope

https://www.sciencedirect.com/science/article/pii/0097849390900667

### PR DESCRIPTION
**Pull request by schillic**
Closes #599.

### CODE REVIEW

File: src/VPolytope.jl [hunk 1]
```diff
@@ -101,6 +102,77 @@ function σ(d::AbstractVector{N},
...
+"""
+function ∈(x::AbstractVector{N}, P::VPolytope{N};
+           solver=GLPKSolverLP(method=:Simplex))::Bool where {N<:Real}
+    vertices = P.vertices
+
+    # special cases: 0 or 1 vertex
+    if length(vertices) == 0
+        return false
+    elseif length(vertices) == 1
+        return x == vertices[1]
```
Comment (mforets) [inline src/VPolytope.jl]:
```suggestion
        return _isapprox(x, vertices[1])
```

File: src/VPolytope.jl [hunk 2]
```diff
@@ -101,6 +102,77 @@ function σ(d::AbstractVector{N},
...
+    end
+
+    @assert length(x) == dim(P)
```
Comment (mforets) [inline src/VPolytope.jl]:
```suggestion
    @assert length(x) == dim(P) "a vector of length $(length(x)) cannot be contained in a polytope of dimension $(dim(P))"
```

File: src/VPolytope.jl [hunk 3]
```diff
@@ -101,6 +102,77 @@ function σ(d::AbstractVector{N},
...
+
+    m, n = length(vertices), length(x)
```
Comment (mforets) [inline src/VPolytope.jl]: simplification: `length(x)` is used a couple of times above, you could move it on top 

```julia
isempty(P) && return false
vertices = P.vertices
m, n = length(vertices), length(first(vertices))
...
```

File: src/VPolytope.jl [hunk 4]
```diff
@@ -101,6 +102,77 @@ function σ(d::AbstractVector{N},
...
+    A = Matrix{N}(undef, n+1, m)
```
Comment (mforets) [inline src/VPolytope.jl]: equivalent to the loops below, but for the sake of mentioning it:

```julia
A = [hcat(vertices...); ones(1, m)]
```

File: src/VPolytope.jl (hunk 1 above)
Comment (schillic) [reply src/VPolytope.jl]: This would be inconsistent with [`VPolygon`](https://github.com/JuliaReach/LazySets.jl/blob/master/src/VPolygon.jl#L321) and other types. There is #126 which could be implemented in such a way, but we also need #1028. I suggest we keep this version for now.

File: src/VPolytope.jl (hunk 4 above)
Comment (schillic) [reply src/VPolytope.jl]: Thanks. I keep mine now that it is already writte.

**Comment by schillic** [comment]
Happy with the new commit?
