### PR TITLE
#820 - Vertices list of polyhedron

### LINKED ISSUE #820: vertices_list of HPolyhedron
Does it make sense to have this? Currently we create it from the constraints, which is clearly wrong.

```julia
julia> plot(LazySets.HPolyhedron{Float64}(LazySets.HalfSpace{Float64}[
LazySets.HalfSpace{Float64}([-1.0, 0.0, 0.0, 0.0], 0.0),
LazySets.HalfSpace{Float64}([-0.714286, -1.0, 0.0, 0.0], 0.0)
]));
ERROR: BoundsError: attempt to access 16-element Array{Array{Float64,1},1} at index [16:30]
```

### PR DESCRIPTION
**Pull request by mforets**
Closes #820.

### CODE REVIEW

File: src/HPolyhedron.jl [hunk 1]
```diff
@@ -395,64 +395,40 @@ function tovrep(P::HPoly{N};
...
-    if length(P.constraints) == 0
-        return Vector{N}(undef, Vector{N}(undef, 0))
-    end
-    @assert isdefined(Main, :Polyhedra) "the function `vertices_list` needs " *
-                                        "the package 'Polyhedra' to be loaded"
-    P = polyhedron(P, backend)
-    prunefunc(P)
-    return collect(points(P))
+function vertices_list(P::HPolyhedron{N}) where {N<:Real}
+    error("the list of vertices of a (possibly unbounded) polyhedron is not defined;" *
```
Comment (schillic) [inline src/HPolyhedron.jl]:
```suggestion
    error("the list of vertices of a (possibly unbounded) polyhedron is not defined; " *
```

File: src/HPolyhedron.jl [hunk 2]
```diff
@@ -395,64 +395,40 @@ function tovrep(P::HPoly{N};
...
+          "if the polyhedron is bounded try converting to `HPolytope` first")
```
Comment (schillic) [inline src/HPolyhedron.jl]:
```suggestion
          "if the polyhedron is bounded, try converting to `HPolytope` first")
```

File: src/HPolyhedron.jl [hunk 3]
```diff
@@ -462,14 +438,16 @@ Return the vertices of a polyhedron in H-representation as a list of singletons.
...
 ### Output
 
-List containing a singleton for each vertex.
+This function returns an error because the polyhedron is possibly unbounded.
+If `P` is known to be bounded, try converting to `HPolytope` first.
 """
-function singleton_list(P::HPolyhedron{N})::Vector{Singleton{N}} where {N<:Real}
-    return [Singleton(vi) for vi in vertices_list(P)]
+function singleton_list(P::HPolyhedron{N}) where {N<:Real}
+    error("the list of singletons of a (possibly unbounded) polyhedron is not defined;" *
```
Comment (schillic) [inline src/HPolyhedron.jl]:
```suggestion
    error("the list of singletons of a (possibly unbounded) polyhedron is not defined; " *
```

File: src/HPolyhedron.jl [hunk 4]
```diff
@@ -462,14 +438,16 @@ Return the vertices of a polyhedron in H-representation as a list of singletons.
...
+          "if the polyhedron is bounded try converting to `HPolytope` first")
```
Comment (schillic) [inline src/HPolyhedron.jl]:
```suggestion
          "if the polyhedron is bounded, try converting to `HPolytope` first")
```

File: src/HPolytope.jl [hunk 5]
```diff
@@ -100,3 +102,81 @@ end
...
+### Input
+
+- `P` -- polytope
+
+### Output
+
+List containing a singleton for each vertex.
+"""
+function singleton_list(P::HPolytope{N}) where {N<:Real}
+    return [Singleton(vi) for vi in vertices_list(P)]
```
Comment (schillic) [inline src/HPolytope.jl]: I think we can remove this implementation. It is [already defined for `AbstractPolytope`](https://github.com/JuliaReach/LazySets.jl/blob/master/src/AbstractPolytope.jl#L52).
