### PR TITLE
#2135 - Convert affine map of a zonotope to a zonotope

### LINKED ISSUE #2135: Convert affine map of a zonotope to a zonotope
```julia
julia> convert(Zonotope, rand(2, 2) * rand(Zonotope))
Zonotope{Float64,Array{Float64,1},Array{Float64,2}}([-1.0351425316188279, 0.14250156266501757], [-0.37320651514909564 -0.41229777241803; 0.365901339997
06076 -0.8906792582447461])

julia> convert(Zonotope, rand(2, 2) * rand(Zonotope) ⊕ rand(2))
ERROR: MethodError: Cannot `convert` an object of type
  AffineMap{Float64,Zonotope{Float64,Array{Float64,1},Array{Float64,2}},Float64,Array{Float64,2},Array{Float64,1}} to an object of type
  Zonotope
Closest candidates are:
  convert(::Type{Zonotope}, ::Zonotope) at /home/mforets/.julia/dev/LazySets/src/convert.jl:8
  convert(::Type{Zonotope}, ::Singleton{N,VN}) where {N, VN<:AbstractArray{N,1}} at /home/mforets/.julia/dev/LazySets/src/convert.jl:282
  convert(::Type{Zonotope}, ::AbstractHyperrectangle{N}) where N at /home/mforets/.julia/dev/LazySets/src/convert.jl:259
  ...
Stacktrace:
 [1] top-level scope at REPL[8]:1
```

xref: https://github.com/JuliaReach/ReachabilityAnalysis.jl/pull/127

### PR DESCRIPTION
**Pull request by schillic**
Closes #2135.

### CODE REVIEW

File: src/convert.jl [hunk 1]
```diff
@@ -979,3 +979,10 @@ end
 function convert(::Type{HalfSpace{N, Vector{N}}}, hs::HalfSpace{N, <:AbstractVector{N}}) where {N}
     return HalfSpace(Vector(hs.a), hs.b)
 end
+
+function convert(::Type{Zonotope},
+                 am::AbstractAffineMap{N, <:AbstractZonotope{N}}) where {N<:Real}
+    Z1 = convert(Zonotope, linear_map(matrix(am), set(am)))
+    Z2 = translate(Z1, vector(am))
```
Comment (mforets) [inline src/convert.jl:986]:
```suggestion
    Z2 = translate(Z1, vector(am), share=true)
```
