### PR TITLE
Fix hyperrectangle plot

### LINKED ISSUE #272: Fix hyperrectangle plot
for example, `h = Hyperrectangle(center=[0.005, 1.1], radius=[0.005, 0.861785])` displays two triangles.

### PR DESCRIPTION
**Pull request by mforets**
Closes #272.

### CODE REVIEW

**Comment by schillic** [comment]
Also fix the vector version?

File: src/plot_recipes.jl [hunk 1]
```diff
@@ -65,7 +79,7 @@ julia> plot([B1, B2])
 
     for S in arr
         Pi = Approximations.overapproximate(S)
-        vlist = hcat(vertices_list(Pi)...).'
+        vlist = hcat(convex_hull(vertices_list(P))...).'
```
Comment (schillic) [inline src/plot_recipes.jl]: `Pi`?

Comment (mforets) [reply src/plot_recipes.jl]: ooops
