### PR TITLE
Some v0.7 and library fixes

### LINKED ISSUE #558: Warning: Error requiring Polyhedra from LazySets
```julia
$ julia7
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0 (2018-08-08 06:46 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin14.5.0

julia> using LazySets, Polyhedra
┌ Warning: Error requiring Polyhedra from LazySets:
│ ArgumentError: Package LazySets does not have CDDLib in its dependencies:
│ - If you have LazySets checked out for development and have
│   added CDDLib as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with LazySets
│ Stacktrace:
│  [1] require(::Module, ::Symbol) at ./loading.jl:830
│  [2] top-level scope at /Users/forets/.julia/dev/LazySets/src/HPolytope.jl:206
│  [3] eval at ./boot.jl:319 [inlined]
│  [4] eval at /Users/forets/.julia/dev/LazySets/src/LazySets.jl:4 [inlined]
│  [5] load_polyhedra() at /Users/forets/.julia/dev/LazySets/src/init.jl:6
│  [6] top-level scope at none:0
│  [7] eval at ./boot.jl:319 [inlined]
│  [8] eval at /Users/forets/.julia/dev/LazySets/src/LazySets.jl:4 [inlined]
│  [9] (::getfield(LazySets, Symbol("##47#50")))() at /Users/forets/.julia/packages/Requires/9Jse8/src/require.jl:67
│  [10] err(::getfield(LazySets, Symbol("##47#50")), ::Module, ::String) at /Users/forets/.julia/packages/Requires/9Jse8/src/require.jl:38
│  [11] #46 at /Users/forets/.julia/packages/Requires/9Jse8/src/require.jl:66 [inlined]
│  [12] withpath(::getfield(LazySets, Symbol("##46#49")), ::String) at /Users/forets/.julia/packages/Requires/9Jse8/src/require.jl:28
│  [13] (::getfield(LazySets, Symbol("##45#48")))() at /Users/forets/.julia/packages/Requires/9Jse8/src/require.jl:65
│  [14] #invokelatest#1 at ./essentials.jl:691 [inlined]
│  [15] invokelatest at ./essentials.jl:690 [inlined]
│  [16] #3 at /Users/forets/.julia/packages/Requires/9Jse8/src/require.jl:19 [inlined]
│  [17] iterate at ./generator.jl:47 [inlined]
│  [18] _collect(::Array{Function,1}, ::Base.Generator{Array{Function,1},getfield(Requires, Symbol("##3#4"))}, ::Base.EltypeUnknown, ::Base.HasShape{1}) at ./array.jl:632
│  [19] map at ./array.jl:561 [inlined]
│  [20] loadpkg(::Base.PkgId) at /Users/forets/.julia/packages/Requires/9Jse8/src/require.jl:19
│  [21] #invokelatest#1 at ./essentials.jl:691 [inlined]
│  [22] invokelatest at ./essentials.jl:690 [inlined]
│  [23] require(::Base.PkgId) at ./loading.jl:855
│  [24] macro expansion at ./logging.jl:311 [inlined]
│  [25] require(::Module, ::Symbol) at ./loading.jl:834
│  [26] eval(::Module, ::Any) at ./boot.jl:319
│  [27] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:85
│  [28] macro expansion at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:117 [inlined]
│  [29] (::getfield(REPL, Symbol("##28#29")){REPL.REPLBackend})() at ./task.jl:262
└ @ Requires ~/.julia/packages/Requires/9Jse8/src/require.jl:40

julia> for N in [Float64]
           cms = CacheMinkowskiSum(2, N)
           z = ZeroSet{N}(2)
           cms + z
       end
```

### LINKED ISSUE #691: Use Polyhedra/CDDLib in new Julia versions

### PR DESCRIPTION
**Pull request by schillic**
Closes #691.
Closes #558.

### CODE REVIEW

File: src/init.jl [hunk 1]
```diff
@@ -4,6 +4,7 @@ function __init__()
 end
 
 function load_polyhedra()
+    @eval using CDDLib # default backend
```
Comment (mforets) [inline src/init.jl]: i think this line should be removed

File: src/HPolyhedron.jl [hunk 2]
```diff
@@ -490,11 +491,16 @@ Determine whether a polyhedron is empty.
...
 LP whose feasible set is determined by the set of constraints and whose
 objective function is zero.
+
+### Notes
+
+This implementation uses `GLPKSolverLP` as linear programming backend by
+default.
 """
-function isempty(P::HPoly{N})::Bool where {N<:Real}
+function isempty(P::HPoly{N}; solver=GLPKSolverLP())::Bool where {N<:Real}
```
Comment (mforets) [inline src/HPolyhedron.jl]: can you pass `backend` option as well to the `polyhedron` constructor?
