### PR TITLE
fix intersection

### LINKED ISSUE #843: Empty polyhedra intersection is broken
```julia
julia> using LazySets, Polyhedra

julia> H = LazySets.HalfSpace([-1.0], -21.0); # x >= 21

julia> P = HPolytope([LazySets.HalfSpace([1.0], 18.1), # x <= 18.1
                      LazySets.HalfSpace([-1.0], -18.0)]); # x >= 18
```
In v0.6 this results in:
```julia
julia> cap = intersection(H, P)
LazySets.HPolytope{Float64}(LazySets.HalfSpace{Float64}[
 LazySets.HalfSpace{Float64}([1.0], 18.1),
 LazySets.HalfSpace{Float64}([-1.0], -18.0),
 LazySets.HalfSpace{Float64}([-1.0], -18.1),
 LazySets.HalfSpace{Float64}([1.0], 18.0)])

julia> isempty(cap)
true
```
In v0.7 this results in:
```julia
julia> cap = intersection(H, P)
HPolytope{Float64}(LazySets.HalfSpace{Float64}[])

julia> isempty(cap)
false
```
Problems:
1. Why does v0.6 not simplify?
It might be because the simplification with `CDDLib` is hard to interpret (contains two hyperplanes):
```julia
julia> Q = polyhedron(cap, CDDLib.CDDLibrary())
Polyhedron CDDLib.CDDPolyhedron{1,Float64}:
4-element iterator of Polyhedra.HalfSpace{1,Float64,Array{Float64,1}}:
 HalfSpace([1.0], 18.1)
 HalfSpace([-1.0], -18.0)
 HalfSpace([-1.0], -18.1)
 HalfSpace([1.0], 18.0)

julia> removehredundancy!(Q)

julia> Q
Polyhedron CDDLib.CDDPolyhedron{1,Float64}:
2-element iterator of Polyhedra.HyperPlane{1,Float64,Array{Float64,1}}:
 HyperPlane([1.0], 18.1)
 HyperPlane([-1.0], -18.0)
```
2. The v0.7 result (polyhedron without constraints) is due to #842. By hard-coding a `1` in the code, the result is as follows:
```julia
julia> cap = intersection(H, P)
HPolytope{Float64}(LazySets.HalfSpace{Float64}[HalfSpace{Float64}([1.0], 0.0), HalfSpace{Float64}([0.0], 1.0), HalfSpace{Float64}([-1.0], -0.0), HalfSpace{Float64}([-0.0], -1.0)])
```
This is still a strange result.

3. Assuming that the v0.7 result (polyhedron without constraints) can occur after fixing #842: This polytope is not empty by definition. But it seems that `Polyhedra` interprets it like that. We should catch this case in the `intersection` methods and return an `EmptySet` in this case. Maybe we should check if `Polyhedra` returns a specific status flag or something to indicate empty intersections.

### PR DESCRIPTION
**Pull request by mforets**
Closes #843.

### CODE REVIEW

File: src/concrete_intersection.jl [hunk 1]
```diff
@@ -400,7 +400,11 @@ function intersection(P1::HPoly{N},
...
         end
         # here, detection of empty intersection may be reported as an infeasible LP
-        remove_redundant_constraints!(Q, backend=backend)
+        if remove_redundant_constraints!(Q, backend=backend)
+            return Q
+        else
+            return EmptySet{N}()
+        end
     end
     return Q
```
Comment (schillic) [inline src/concrete_intersection.jl]: The `return Q` at the end of the function could be pulled inside the `if` case above to make the flow clearer.
